export default {
	credits: "Pomi108, iFixtronCZ",
	global: {
		name: "Faithful",
		login: "Přihlásit se",
		logout: "Odhlásit se",
		success_message: "Povedlo se!",
		loading: "Načítám, prosím vyčkejte…",
		no_results: "Žádné výsledky",
		nyi: "Zatím neimplementováno",
		invalid_url: "Tato URL adresa není platná",
		navbar: {
			labels: {
				sidebar: "Přepnout postranní panel",
				theme: "Přepnout rozevírací nabídku motivů",
				translations: "Přepnout rozevírací nabídku překladů",
				user: "Přihlášeno jako %s",
			},
			translations: {
				title: "Překlady",
				crowdin: "Pomoct s překladem",
			},
			profile: {
				view: "Váš profil",
				main_site: "Webová stránka resourcepacku Faithful",
				manage: "Spravovat účty",
				copy: "Zkopírovat ID uživatele",
				copied: "ID uživatele zkopírováno do schránky",
			},
		},
		connection: {
			logo: "Logo resourcepacku Faithful",
			description: "Problémy s připojením?",
			contact: "Kontaktujte nás",
			status: "Stav služeb Faithful",
		},
		footer: {
			credits: "Tato stránka byla vytvořena pomocí komponentového frameworku %Vuetify%.",
			source: "Zdrojový kód si můžeš zobrazit %zde%!",
			copyright: "© %d Faithful Resource Pack",
		},
		themes: {
			notification: "Systémový motiv změněn na %s",
			dark_sidebar: "Tmavý postranní panel",
			title: "Motivy",
			options: {
				light: "světlý",
				dark: "tmavý",
				system: "systémový",
			},
		},
		btn: {
			add: "Přidat",
			submit: "Odeslat",
			submit_for_review: "Odeslat ke kontrole",
			submit_and_approve: "Odeslat a schválit",
			cancel: "Zrušit",
			close: "Zavřít",
			copy: "Kopírovat",
			save: "Uložit",
			edit: "Upravit",
			delete: "Smazat",
			ok: "OK",
			yes: "Ano",
			deny: "Zamítnout",
			confirm: "Potvrdit",
			approve: "Schválit",
			archive: "Archivovat",
			load_more: "Načíst více",
			reset: "Resetovat formulář",
			report: "Nahlásit",
			publish: "Zveřejnit",
			save_draft: "Uložit jako koncept",
		},
		tabs: {
			general: {
				title: "Obecné",
				subtabs: {
					dashboard: "Nástěnka",
					profile: "Profil",
					gallery: "Galerie",
				},
			},
			addons: {
				title: "Doplňky",
				subtabs: {
					new: "Nový add-on",
					submissions: "Přihlášky",
					review: "Zkontrolovat",
				},
			},
			posts: {
				title: "Příspěvky",
				subtabs: {
					create: "Vytvořit příspěvek",
					all: "Všechny příspěvky",
				},
			},
			database: {
				title: "Databáze",
				subtabs: {
					contributions: "Příspěvky",
					users: "Uživatelé",
					textures: "Textury",
					versions: "Verze",
					packs: "Packy",
					settings: "Nastavení",
				},
			},
		},
		json_editor: {
			import_data: "Importovat JSON data",
			parse_json: "Převést JSON na data",
		},
		datepicker: {
			year: "Rok",
			month: "Měsíc",
			day: "Den",
		},
		tabbed_text_field: {
			write: "Napsat",
			preview: "Zobrazit náhled",
			empty: "Nic k zobrazení",
		},
		drop_zone: {
			standby_singular: "Přetáhněte soubor nebo klikněte pro výběr",
			standby_plural: "Přetáhněte soubory nebo klikněte pro výběr",
			dragging_singular: "Uvolněním nahrajete soubor",
			dragging_plural: "Uvolněním nahrajete soubory",
		},
		account_manager: {
			title: "Správce účtů",
			active_account: "Aktivní účet",
			add_account: "Přidat nový účet",
			switch_accounts: "Přepnout na účet",
			avatar_alt_text: "Avatar uživatele %s",
		},
		emitting_image: {
			fullscreen: "Otevřít v režimu celé obrazovky",
			delete: "Odstranit obrázek",
		},
	},
	missing_page: {
		title: "Jseš v koncích?",
		description: "Bohužel, stránka, kterou jste požadovali, neexistuje!",
		main_page:
			"Zkontrolujte, zda nemáte překlep nebo přejděte na %hlavní stránku%, kde najdete to, co jste hledali.",
	},
	dashboard: {
		welcome: "Vítejte ve Faithful Studiu!",
		welcome_user: "Vítej, uživateli %USER%!",
		totals: {
			authors: "autorů",
			contributions: "příspěvků",
			last_year: "příspěvků za loňský rok",
			last_month: "příspěvků minulý měsíc",
			last_week: "příspěvků minulý týden",
			last_day: "příspěvků za posledních 48 hodin",
		},
		titles: {
			profile: "Váš profil",
			textures: "Textury",
			addons: "Doplňky",
			contribution_stats: "Příspěvky",
			contribution_activity: "Aktivita přispívání",
		},
		profile: {
			login_notice: "Pro získání více funkcí se přihlaste!",
			login_button: "Přihlásit přes Discord",
		},
		addons: {
			submissions: "Příspěvky",
			upload: "Nahrání",
		},
		textures: {
			total: "Textury",
			versions: "Verze",
		},
		locale: {
			on: " ",
			less: "Více",
			more: "Méně",
		},
	},
	profile: {
		title: "Profil",
		public_profile: "Přejít na veřejný profil",
		general: {
			title: "Obecné",
			username: {
				label: "Uživatelské jméno",
				hint: "Tvoje uživatelské jméno bude využito na webových stránkách pro příspěvky, doplňky atd.",
				rules: {
					min: "Uživatelské jméno musí obsahovat více než %d znaků",
					max: "Uživatelské jméno musí obsahovat méně než %d znaků",
				},
			},
			uuid: {
				label: "UUID Minecraft profilu",
				hint: "Váš skin bude zobrazen na vaší stránce profilu a v add-onech",
				skin_alt_text: "Minecraftový skin",
				rules: {
					length: "UUID musí obsahovat přesně 36 znaků",
				},
			},
			bio: {
				label: "Bio",
				placeholder: "Bio",
				hint: "Bio můžeš vyšperkovat formátováním Markdown!",
				rules: {
					length: "Bio musí obsahovat méně než %d znaků",
				},
			},
			anonymous: {
				label: "Anonym",
				hint: "Zakáže stránku profilu a skryje uživatelské jméno a Minecraftový skin v galerii textur. Uživatelské jméno bude stále viditelné v odeslaných texturách pro účely kreditace, avšak nezobrazí se nikde jinde.",
			},
		},
		social: {
			title: "Odkazy na sociální sítě",
			add: "Přidat sociální sítě",
			remove: "Odstranit sociální sítě",
			type: {
				label: "Typ sociální sítě",
				rules: {
					exists: "Typ sociální sítě je povinný",
					valid: "Typ sociální sítě musí být platný",
				},
			},
			link: {
				label: "Odkaz na profil na sociálních sítích",
				placeholder: "https://www.priklad-odkazu.cz/",
				rules: {
					valid: "URL musí být platné.",
				},
			},
		},
		save_changes: "Uložit změny",
		delete: {
			title: "Smazání účtu",
			btn: "Smazat účet",
			warning: "Tento proces je nevratný!",
			addons: {
				title_singular: "Toto ovlivní %d add-on",
				title_plural: "Toto ovlivní %d addony/ů",
				deleted: "Smazáno",
				transferred: "Převedeno jiným autorům",
			},
		},
	},
	gallery: {
		title: "Galerie",
		max_items_per_row: "Maximální počet položek na řádku",
		stretched_switcher: "Zobrazení na celou šířku",
		animated_switcher: "Přehrávat animované textury",
		share: "Sdílet texturu",
		to_top: "Vrátit se na začátek stránky",
		share_link_copied_to_clipboard: "Odkaz pro sdílení zkopírován do schránky",
		authors_copied_to_clipboard: "Autoři odeslaných textur zkopírováni do schránky",
		loading_message: "Načítání výsledků z galerie…",
		error_message: {
			texture_not_done: "Textura chybí nebo byla schválně vynechána.",
			user_anonymous: "Anonym",
			user_not_found: "Neznámý uživatel",
			contribution_not_found: "V databázi nebyli nalezeni žádní autoři!",
			search_failed: "Hledání se nezdřilo",
		},
		category: {
			pack: "Pack",
			edition: "Edice",
			mc_version: "Minecraft verze",
			tag: "Tag",
			search: "Vyhledat",
		},
		sort: {
			name_asc: "Název (A → Z)",
			name_desc: "Název (Z → A)",
			id_asc: "ID textury (nejmenší → největší)",
			id_desc: "ID textury (největší → nejmenší)",
			contrib_desc: "Nedávno odeslána",
		},
		tooltip: {
			modded: "Módovaná textura",
			mojang: "Mojang Studios",
			ignored: "Ignorovaná textura",
		},
		all: "vše",
		latest: "Nejnovější",
		clear_cache: "Smazat mezipaměť galerie",
		result_stats_singular: "%COUNT% textura nalezena za %SECONDS% sekund",
		result_stats_plural: "%COUNT% textur/y nalezeno/y za %SECONDS% sekund",
		modal: {
			no_contributions: "Nebyly nalezeny žádné příspěvky",
			image_alt_text: "Textura %NAME% pro pack %PACK%",
			loading: "Načítání textury…",
			ignored:
				"Tato textura byla ignorována a nemusela být zvětšena (upscalována) ve všech projektech!",
			tabs: {
				information: "Informace",
				authors: "Autoři",
				animation: "Animace",
			},
			info: {
				texture: "Textura",
				uses: "Využití",
				paths: "Cesty",
			},
			animation: {
				texture_mcmeta: "MCMETA",
			},
			data: {
				contribution_id: "ID příspěvku",
				date: "Datum",
				authors: "Autor/Autoři",
				id: "ID",
				name: "Jméno",
				tags: "Kategorie",
				use_id: "ID využití",
				use_name: "Jméno využití",
				edition: "Edice",
				texture_id: "ID textury",
				path_id: "ID cesty",
				resource_pack_path: "Cesta v resource packu",
				mc_versions: "Verze Minecraftu",
			},
		},
	},
	addons: {
		titles: {
			submit: "Nahrát nový doplněk",
			edit: "Upravit doplňky",
			submissions: "Přihlášky",
			details: "Podrobnosti",
		},
		remove: {
			title: "Potvrdit smazání",
			description: '"%s" bude smazán navždy. Toto nelze vrátit zpět.',
		},
		general: {
			loading_addon: "Načítám doplněk…",
			no_submissions: "Aktuálně nemáš žádné odeslané add-ony!",
			go_to_addon: "Zobrazit veřejný seznam add-onů",
			rules: "Před odesláním si nezapomeňte přečíst pravidla pro add-ony",
			title: "Obecné",
			name: {
				label: "Název doplňku",
				hint: "Čím kratší, tím lepší. (Ale nepřežeň to!)",
				rules: {
					name_required: "Název je vyžadován.",
					name_too_big: "Název doplňku musí být kratší než %s znaků.",
					name_too_small: "Název doplňku musí být alespoň %s znaků dlouhý.",
					name_unavailable: "Tento název už je používán jiným doplňkem!",
				},
			},
			slug: {
				label: "Slug doplňku",
				hint: "Změna tohoto nastavení rozbije staré odkazy!",
			},
			reason: {
				title: "Důvod aktualizace",
				text: "Buďte prosím co nejkonkrétnější, abyste nám ulehčili kontrolu vašeho add-onu!",
				required: "Je vyžadován důvod aktualizace",
				bounds: "Důvod aktualizace musí mít délku mezi %s a %s znaky",
			},
			authors: {
				label: "Vyber autory doplňku",
				hint: "Jakmile je doplněk nahrán, jakýkoliv autor ho může upravit! | Pokud v seznamu někoho nemůžeš najít, kontaktuj nějakého administrátora či vývojáře",
			},
		},
		info: {
			title: "Informace",
			description: {
				placeholder: "Popisek doplňku",
				hint: "Popisek můžete vyšperkovat formátováním Markdown!",
				rules: {
					description_required: "Popisek je povinný",
					description_too_big: "Popisek musí obsahovat více než %s znaků",
					description_too_small: "Popisek musí obsahovat alespoň %s znaků",
				},
			},
			embed_description: {
				label: "Popis vloženého obrázku",
				hint: "Popis zobrazen při sdílení doplňku na sociálních sítích",
				rules: {
					too_big: "Popisek vloženého obrázku musí obsahovat méně než %s znaků",
				},
			},
		},
		images: {
			title: "Obrázky",
			header: {
				labels: {
					drop: "Kliknutím vyberte obrázek záhlaví",
					normal: "Hlavní obrázek",
					replace: "Změnit hlavní obrázek",
				},
				rules: {
					image_size:
						"Velikost obrázku musí být méně než %s KB! (Ke kompresi můžeš využít https://compressor.io/.)",
					image_ratio: "Nesprávný poměr stran: Nahraný obrázek musí mít poměr stran 16:9.",
					image_required: "Hlavní obrázek je vyžadován.",
					jpeg: "Obrázek musí být JPEG se ztrátovou kompresí",
					compress: "Ke kompresi můžeš využít https://compressor.io/",
				},
				status: {
					upload: "Obrázek záhlaví byl úspěšně nahrán",
					remove: "Obrázek záhlaví byl úspěšně odstraněn",
				},
			},
			screenshots: {
				labels: {
					drop: "Kliknutím vyberte další obrázky",
					normal: "Další obrázky",
					replace: "Změnit další obrázky",
				},
				rule: "Nesprávný poměr stran: Všechny obrázky s poměrem stran jiným než 16:9 byly odstraněny",
				status: {
					upload: "Obrázek úspěšně nahrán",
					remove: "Obrázek úspěšně odstraněn",
				},
			},
		},
		compatibility: {
			title: "Kompatibilita",
			optifine: {
				label: "Vyžaduje OptiFine",
			},
			editions: {
				label: "Podporované edice",
			},
			packs: {
				label: "Podporované packy",
			},
		},
		downloads: {
			title: "Odkazy na stažení",
			add_group: "Přidat skupinu pro stažení",
			add_item: "Přidat odkaz ke stažení do skupiny",
			remove_group: "Odstranit skupinu pro stažení a její položky",
			remove_item: "Odstranit odkaz ke stažení ze skupiny",
			name: {
				placeholder: "Odkaz na CurseForge, GitHub…",
				label: "Jméno",
				rules: {
					name_required: "Jméno je vyžadováno.",
					name_cannot_be_empty: "Jméno nemůže být prázdné.",
				},
			},
			link: {
				placeholder: "https://www.příklad.cz/",
				label: "Odkaz",
				rule: "URL musí být platné.",
			},
		},
		status: {
			approved: "Schváleno",
			denied: "Zamítnuto",
			pending: "Čeká na schválení",
			archived: "Archivováno",
		},
	},
	review: {
		titles: {
			addons: "Posoudit doplňky",
			pending: "Čekající na schválení",
			denied: "Zamítnuto",
			approved: "Schváleno",
			archived: "Archivováno",
		},
		reason_modal: {
			deny_title: "Zamítnout doplněk",
			archive_title: "Archivovat add-on",
			warning: "Všichni autoři mohou tento důvod vidět!",
			label: "Napiš důvod…",
		},
		labels: {
			pending: "Momentálně nejsou žádné doplňky čekající na schválení!",
			denied: "Momentálně nejsou žádné zamítnuté doplňky!",
			archived: "Aktuálně nejsou k dispozici žádné archivované add-ony!",
			approved: "Aktuálně nejsou k dispozici žádné schválené add-ony!",
			search: "Hledat add-ony",
		},
		addon: {
			titles: {
				last_updated: "Naposledy aktualizován %s",
				unknown_date: "Poslední aktualizace tohoto add-onu neznámá",
				compatibility: "Kompatibilita",
				author_singular: "Autor",
				author_plural: "Autoři",
				description: "Popis",
				download_singular: "Stažení",
				download_plural: "Stahování",
			},
			labels: {
				optifine: "Vyžaduje OptiFine",
				approved_by: "Schváleno administrátorem %s",
				denied_by: "Zamítnuto administrátorem %s",
				archived_by: "Archivováno administrátorem %s",
				unknown_status: "Neznámý stav kontroly (%s)",
				reason: "Důvod",
				no_reason: "Žádný důvod nebyl uveden",
			},
		},
	},
	posts: {
		titles: {
			list: "Všechny příspěvky",
			edit: "Upravit příspěvek",
			new: "Vytvořit nový příspěvek",
		},
		status: {
			published: "Publikováno %s",
			draft: "Koncept",
		},
		loading: "Načítání příspěvku…",
		go_to_post: "Zobrazit odeslaný příspěvek",
		general: {
			heading: "Obecné",
			title: {
				label: "Nadpis příspěvku",
				placeholder: "Chytrá lednice Faithful: Alpha 1",
			},
			permalink: {
				label: "Stálý odkaz",
				placeholder: "/chytralednice-faithful/A1",
			},
			header_img: {
				label: "Obrázek záhlaví (volitelné)",
				hint: "Poznámka: Toto musí být nahráno samostatně",
				placeholder: "https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg",
			},
			date: {
				label: "Datum vydání příspěvku",
			},
			discontinued: {
				label: "Podpora ukončena",
				hint: "Pokud je toto pole zaškrtnuto, příspěvek bude označen jako ukončený",
			},
			description: {
				placeholder: "Popis příspěvku",
				hint: "Popisek můžete vyšperkovat formátováním Markdown!",
			},
		},
		download: {
			heading: "Stahování",
			add_category: "Přidat kategorii stahování",
			add_item_to_category: "Přidat stažení do kategorie",
			add_single_item: "Přidat jedno stažení",
			remove_category: "Odstranit kategorii pro stahování a její položky",
			remove_item_in_category: "Odstranit stažení z kategorie",
			remove_single_item: "Odstranit jedno stažení",
			category: "Název kategorie stažení",
			name: "Název stažení",
			link: "Odkaz pro stažení",
			link_placeholder: "https://www.priklad-odkazu.cz/",
		},
		changelog: {
			heading: "Seznam změn",
			add_category: "Přidat kategorii seznamu změn",
			add_item: "Přidat položku seznamu změn",
			remove_category: "Odstranit kategorii seznamu změn",
			remove_item: "Odstranit položku seznamu změn",
			import_json: "Importovat JSON",
			open_category: "Otevřít kategorii seznamu změn",
			close_category: "Sbalit kategorii seznamu změn",
			form_levels: {
				primary: "Primární kategorie",
				secondary: "Sekundární kategorie",
				item_category: "Kategorie položek (Autoři)",
				item: "Položka (Autor)",
			},
		},
		changelog_generator: {
			heading: "Vygenerovat seznam změn",
			date: "Datum od posledního seznamu změn",
			pack: "Seznam změn packu",
			copy: "Zkopírovat do schránky",
			categorize: "Automaticky kategorizovat seznamy změn podle typu (experimentální)",
			categorize_warning:
				"Kvůli způsobu, jakým jsou příspěvky textur sledovány, nemusí být kategorizace podle typu přesná!",
			download: "Stáhnou seznam změn",
			warning: "Před importem seznamu změn si jej prosím ručně zkontrolujte!",
		},
	},
	database: {
		search: "Vyhledat",
		anonymous: "Anonym",
		nameless: "Beze jména",
		summary: "Shrnutí",
		confirm_deletion: "Potvrdit smazání",
		ask_deletion: "Opravdu chceš smazat %s (%d)?",
		contributions: {
			title: "Příspěvky",
			contributors: "Přispěvatelé",
			add_contributions: "Přidat nové příspěvky",
			edit_contribution: "Upravit příspěvek",
			delete_contribution: "Smazat příspěvek",
			pack_filter: "Filtrovat podle packu",
			user_filter: "Uživatelé",
			texture_filter: "Textury",
			select_user: "Vybrat uživatele",
			contribution_count_singular: "%d příspěvek",
			contribution_count_plural: "%d příspěvky/ů",
			authorless: "Nebyly přidáni žádní autoři",
			contribution_result: "Výsledky příspěvků",
			search_contributions: "Vyhledat příspěvky",
			modal: {
				add_new_contribution: "Přidat nový příspěvek",
				clone_contribution: "Naklonovat vybraný příspěvek",
				one_contributor: "Prosím vyber alespoň jednoho uživatele",
				id: "ID příspěvku",
				id_hint: "Změna ID příspěvku může vše rozbít!",
				pack: "Resource pack",
				texture_id: "ID textury",
				texture_ids: "ID textur",
				increment_texture: "Inkrementovat ID textury",
				decrement_texture: "Dekrementovat ID textury",
				id_field_errors: {
					one_required: "Je vyžadováno alespoň jedno ID textury nebo rozsah ID",
					incorrect_value: "Nesprávné ID textury %value% nebo rozsah ID",
				},
			},
		},
		users: {
			title: "Uživatelé",
			role_filter: "Vyber role uživatele",
			search_username: "Vyhledat uživatelské jméno",
			user_result: "Výsledky uživatelů",
			modal: {
				add_user: "Přidat nového přispěvatele",
				edit_user: "Upravit přispěvatele",
				delete_user: "Smazání účtu",
				id: "Discord ID",
				id_hint: "Změna Discord ID aktualizuje veškeré související příspěvky a add-ony",
				username: "Uživatelské jméno",
				uuid: "UUID Minecraft profilu",
				roles: "Role uživatele",
				anonymous: "Anonym",
			},
		},
		textures: {
			title: "Textury",
			add_texture: "Přidat novou texturu",
			add_multiple: "Přidat nové textury",
			edit_texture: "Upravit texturu",
			texture_result: "Výsledky textur",
			tag_filter: "Filtrovat podle tagů",
			search_texture: "Vyhledat jméno textury",
			add_success: "Textury byly úspešně přidány",
			delete_modal: {
				title_texture: "Smazat texturu",
				title_use: "Smazat použití",
				title_path: "Smazat cestu",
				affected_uses: "Ovlivněná použití",
				affected_paths: "Ovlivněné cesty",
				affected_contributions: "Ovlivněné příspěvky",
			},
			modal: {
				title: "Textura",
				subtitle: "Použití a cesty",
				tagless: "Nebyly přidány žádné tagy",
				copy_button: "Zkopírovat data textury jako JSON",
				json_button: "Importovat JSON data",
				persist_button: "Zachovat při uložení",
				copy_json_data: "JSON data zkopírována do schránky",
				id_hint: "Změna ID textury může všechno rozbít!",
				id: "ID textury",
				name: "Jméno textury",
				tags: "Druh textury",
				recompute_tag_list: "Znovu vygenerovat tagy pomocí data cesty",
			},
			uses: {
				title: "Použití",
				singular: "Použití",
				plural: "Použití",
				add_use: "Přidat nové využití",
				edit_use: "Upravit využití",
				add_edition_use: "Přidat automatické použití %edition%",
				no_use_found: "Pro tuto texturu nebyla nalezena žádná použití",
				id_hint: "Změna ID využití může všechno rozbít!",
				id: "ID využití",
				name: "Jméno využití",
				edition: "Edice využití",
			},
			paths: {
				title: "Cesty",
				singular: "Cesta",
				plural: "Cesty",
				add_path: "Přidat novou cestu",
				edit_path: "Upravit cestu",
				no_path_found: "Pro tuto cestu nebyly nalezeny žádné cesty",
				id_hint: "Změna ID cesty může všechno rozbít!",
				id: "ID cesty",
				name_hint: "Cesta by měla začínat z kořenového adresáře (např. assets/…)",
				name_prefill: "Zadejte nejprve toto pro vygenerování většiny polí!",
				name: "Cesta",
				versions: "Verze",
				mcmeta: "Animované",
			},
			merge_textures: {
				title: "Sloučit textury",
				warning: "Toto smaže zdrojovou texturu a nelze to vrátit zpět!",
				source: "ID zdrojové textury",
				destination: "ID cílové textury",
				invalid_id: "Neplatné ID textury",
			},
		},
		versions: {
			title: "Verze",
			edition_filter: "Filtrovat podle edice",
			version_result: "Výsledky edicí",
			exists: "Název verze již existuje",
			path_count_singular: "%d cesta",
			path_count_plural: "%d cest/y",
			no_paths: "Žádné přidružené cesty",
			modal: {
				title: "Upravit verzi Minecraftu",
				name: "Název verze Minecraftu",
				edition: "Edice Minecraftu",
				warning: "Nezapomeňte prosím aktualizovat všechny názvy branchů na GitHubu!",
			},
			add: {
				title: "Přidat novou verzi Minecraftu",
				success: "Verze byla úspěšně přidána",
				new_edition: "Edice, ke které bude verze přidána",
				template_version: "Verze šablony",
				new_version: "Jméno nové verze",
			},
			delete: {
				title: "Smazat verzi Minecraftu",
				description: "Chcete smazat verzi %VERSION% pro edici %EDITION%?",
				no_affected_paths: "Žádné cesty nebudou ovlivněny",
				affected_paths_singular: "%d cesta bude ovlivněna.",
				affected_paths_plural: "%d cest/y bude/budou ovlivněny.",
			},
		},
		packs: {
			title: "Packy",
			tag_filter: "Filtrovat podle tagů",
			pack_result: "Výsledky packů",
			modal: {
				add_pack: "Přidat nový pack",
				edit_pack: "Upravit pack",
				delete_pack: "Smazat pack",
				id: "ID packu",
				id_creation_hint: "ID packu může být buď ručně zadáno nebo automaticky vygenerováno",
				id_editing_hint: "Změna ID packu může všechno rozbít!",
				name: "Název packu",
				tags: "Tagy packu",
				resolution: "Rozlišení packu",
				color: "Barva packu",
				logo: "URL loga packu",
				github: {
					title: "GitHub",
					title_hint: "Edice může být ponechána prázdná, pokud ještě není podporována",
					length_notice: "Musí být přítomen alespoň jeden GitHub repozitář",
					organization: "Organizace",
					repository: "Repozitář",
				},
				delete_hint:
					"Smazáním packu jej odstraníte z galerie textur a Discord botů, ale neovlivníte tím jeho repozitáře na GitHubu.",
			},
			submissions: {
				title: "Informace o příspěvku",
				delete_submission: "Smazat informace o odeslané textuře",
				add_submission: "Přidat informace o příspěvku",
				edit_submission: "Upravit informace o příspěvku",
				reference_pack: "Referenční pack",
				reference_hint: "Pack pro porovnání s vloženými obrázky příspěvků",
				contributor_role: "ID role přispěvatele",
				time_to_results: "Čas do výsledků",
				time_hint: "Zpoždění bývají v řádech dnů",
				channels: {
					title: "Discord kanály",
					title_hint:
						"Povolte Vývojářský režim a klikněte pravým tlačítkem myši na kanál pro získání ID kanálů",
					submit: "Kanál pro příspěvky",
					results: "Kanál pro výsledky",
				},
				delete_warning: "Toto odstraní %d příspěvky/ů!",
			},
		},
		settings: {
			title: "Upravit globální nastavení",
		},
	},
};
