export default {
	credits: "Zesuelpro",
	global: {
		name: "Faithful",
		login: "Iniciar sesión",
		logout: "Cerrar Sesión",
		success_message: "Completado con éxito",
		loading: "Cargando, por favor espere…",
		no_results: "No se encontraron resultados",
		nyi: "Aún no implementado.",
		invalid_url: "Esta URL no es válida",
		navbar: {
			labels: {
				sidebar: "Mostrar/Ocultar la barra lateral",
				theme: "Mostrar/Ocultar el menú de temas",
				translations: "Mostrar/Ocultar el menú de traducciones",
				user: "Sesión iniciada como %s",
			},
			translations: {
				title: "Traducciones",
				crowdin: "Ayuda a traducir",
			},
			profile: {
				view: "Tu perfil",
				main_site: "Sitio web de Faithful",
				manage: "Administrar cuentas",
				copy: "Copiar ID de usuario",
				copied: "ID de usuario copiado al portapapeles",
			},
		},
		connection: {
			logo: "Logo de Faithful",
			description: "¿Problemas de conexión?",
			contact: "Contáctanos",
			status: "Estado de Faithful",
		},
		footer: {
			credits: "Este sitio web se creó con el framework de componentes %Vuetify%.",
			source: "¡Mira el código fuente %aqui%!",
			copyright: "© %d Faithful Resource Pack",
		},
		themes: {
			notification: "El tema del sistema ha cambiado a %s",
			dark_sidebar: "Barra lateral oscura",
			title: "Temas",
			options: {
				light: "Claro",
				dark: "Oscuro",
				system: "Sistema",
			},
		},
		btn: {
			add: "Agregar",
			submit: "Enviar",
			submit_for_review: "Enviar para revisión",
			submit_and_approve: "Enviar y confirmar",
			cancel: "Cancelar",
			close: "Cerrar",
			copy: "Copiar",
			save: "Guardar",
			edit: "Editar",
			delete: "Eliminar",
			ok: "Ok",
			yes: "Sí",
			deny: "Rechazar",
			confirm: "Confirmar",
			approve: "Confirmar",
			archive: "Archivar",
			load_more: "Cargar más",
			reset: "Restablecer formulario",
			report: "Reportar",
			publish: "Publicar",
			save_draft: "Guardar como borrador",
		},
		tabs: {
			general: {
				title: "General",
				subtabs: {
					dashboard: "Panel de control",
					profile: "Perfil",
					gallery: "Galería",
				},
			},
			addons: {
				title: "Complementos",
				subtabs: {
					new: "Nuevo complemento",
					submissions: "Envíos",
					review: "Revisión",
				},
			},
			posts: {
				title: "Publicaciones",
				subtabs: {
					create: "Crear publicación",
					all: "Todas las publicaciones",
				},
			},
			database: {
				title: "Base de datos",
				subtabs: {
					contributions: "Contribuciones",
					users: "Usuarios",
					textures: "Texturas",
					versions: "Versiones",
					packs: "Packs",
					settings: "Ajustes",
				},
			},
		},
		json_editor: {
			import_data: "Importar datos JSON",
			parse_json: "Convertir JSON en datos",
		},
		datepicker: {
			year: "Año",
			month: "Mes",
			day: "Día",
		},
		tabbed_text_field: {
			write: "Escribir",
			preview: "Vista previa",
			empty: "Nada que mostrar en la vista previa",
		},
		drop_zone: {
			standby_singular: "Arrastra un archivo aquí o haz clic para seleccionarlo",
			standby_plural: "Arrastra archivos aquí o haz clic para seleccionarlos",
			dragging_singular: "Suelta para subir el archivo",
			dragging_plural: "Suelta para subir los archivos",
		},
		account_manager: {
			title: "Administrador de cuentas",
			active_account: "Cuenta activa",
			add_account: "Agregar nueva cuenta",
			switch_accounts: "Cambiar a esta cuenta",
			avatar_alt_text: "Avatar de %s",
		},
		emitting_image: {
			fullscreen: "Abrir en pantalla completa",
			delete: "Quitar imagen",
		},
	},
	missing_page: {
		title: "¿Estás perdido en El End?",
		description: "Desafortunadamente, la página solicitada no existe!",
		main_page:
			"Intenta revisar tu ortografía o ir a la %main page% para encontrar lo que estabas buscando.",
	},
	dashboard: {
		welcome: "¡Bienvenido a Faithful Studio!",
		welcome_user: "¡Bienvenido %USER%!",
		totals: {
			authors: "autores",
			contributions: "contribuciones",
			last_year: "contribuciones el año pasado",
			last_month: "contribuciones en el último mes",
			last_week: "contribuciones en la última semana",
			last_day: "contribuciones en las últimas 48 horas",
		},
		titles: {
			profile: "Perfil",
			textures: "Texturas",
			addons: "Complementos",
			contribution_stats: "Contribuciones",
			contribution_activity: "Actividad de contribución",
		},
		profile: {
			login_notice: "¡Inicia sesión para acceder a más funciones!",
			login_button: "Iniciar sesión mediante Discord",
		},
		addons: {
			submissions: "Envíos",
			upload: "Subir",
		},
		textures: {
			total: "Texturas",
			versions: "Versiones",
		},
		locale: {
			on: "en",
			less: "Menos",
			more: "Más",
		},
	},
	profile: {
		title: "Perfil",
		public_profile: "Ir al perfil público",
		general: {
			title: "General",
			username: {
				label: "Nombre de usuario",
				hint: "Tu nombre de usuario se mostrará en servicios de Faithful para contribuciones, complementos, etc.",
				rules: {
					min: "El nombre de usuario debe tener más de %d caracteres",
					max: "El nombre de usuario debe tener menos de %d caracteres",
				},
			},
			uuid: {
				label: "UUID del perfil de Minecraft",
				hint: "Tu skin aparecerá en tu página de perfil y en tus complementos",
				skin_alt_text: "Skin de Minecraft",
				rules: {
					length: "El UUID debe tener exactamente 36 caracteres",
				},
			},
			bio: {
				label: "Acerca de mi",
				placeholder: "Acerca de mi",
				hint: "¡Puedes usar Markdown para darle formato a tu descripción!",
				rules: {
					length: "Tu descripción debe tener menos de %d caracteres",
				},
			},
			anonymous: {
				label: "Anónimo",
				hint: "Desactiva tu página de perfil y oculta tu nombre de usuario y tu skin de Minecraft en la galería de texturas. Tu nombre de usuario aún se podrá ver en los envíos de texturas para darte crédito, pero no aparecerá en ningún otro lugar.",
			},
		},
		social: {
			title: "Enlaces a redes sociales",
			add: "Añadir redes sociales",
			remove: "Quitar red social",
			type: {
				label: "Tipo de red social",
				rules: {
					exists: "El tipo de red social es obligatorio",
					valid: "El tipo de red social debe ser válido",
				},
			},
			link: {
				label: "Enlace al perfil de la red social",
				placeholder: "https://www.ejemplo.com",
				rules: {
					valid: "La URL debe ser válida.",
				},
			},
		},
		save_changes: "Guardar los cambios",
		delete: {
			title: "Eliminar cuenta",
			btn: "Eliminar cuenta",
			warning: "Este proceso es irreversible!",
			addons: {
				title_singular: "Esto afectará a %d complemento",
				title_plural: "Esto afectará a %d complementos",
				deleted: "Eliminados",
				transferred: "Transferidos a otros autores",
			},
		},
	},
	gallery: {
		title: "Galería",
		max_items_per_row: "Máximo de artículos por fila",
		stretched_switcher: "Vista de ancho completo",
		animated_switcher: "Mostrar animaciones",
		share: "Compartir textura",
		to_top: "Volver al inicio de la página",
		share_link_copied_to_clipboard: "Enlace para compartir copiado al portapapeles",
		authors_copied_to_clipboard: "Se copiaron al portapapeles los autores del envío de la textura",
		loading_message: "Cargando resultados de la galería…",
		error_message: {
			texture_not_done: "¡Falta esta textura!",
			user_anonymous: "Anónimo",
			user_not_found: "Usuario desconocido",
			contribution_not_found: "¡No se encontraron contribuciones en la base de datos!",
			search_failed: "La búsqueda falló",
		},
		category: {
			pack: "Pack",
			edition: "Edición",
			mc_version: "Versión de Minecraft",
			tag: "Etiqueta",
			search: "Buscar",
		},
		sort: {
			name_asc: "Nombre (A → Z)",
			name_desc: "Nombre (Z → A)",
			id_asc: "ID de textura (menor → mayor)",
			id_desc: "ID de textura (mayor → menor)",
			contrib_desc: "Contribuido recientemente",
		},
		tooltip: {
			modded: "Textura modificada",
			mojang: "Mojang Studios",
			ignored: "Textura Ignorada",
		},
		all: "Todos",
		latest: "Reciente",
		clear_cache: "Borrar caché de Galería",
		result_stats_singular: "Textura %COUNT% encontrada en %SECONDS% segundos",
		result_stats_plural: "%COUNT% texturas encontradas en %SECONDS% segundos",
		modal: {
			no_contributions: "No se ha encontrado ninguna contribución",
			image_alt_text: "Textura %NAME% para el paquete %PACK%",
			loading: "Cargando textura…",
			ignored:
				"¡Esta textura ha sido ignorada y no puede ser escalada a mayor resolución para todos los proyectos!",
			tabs: {
				information: "Información",
				authors: "Autores",
				animation: "Animación",
			},
			info: {
				texture: "Textura",
				uses: "Usos",
				paths: "Rutas",
			},
			animation: {
				texture_mcmeta: "MCMETA",
			},
			data: {
				contribution_id: "ID de contribución",
				date: "Fecha",
				authors: "Autores",
				id: "ID",
				name: "Nombre",
				tags: "Etiquetas",
				use_id: "ID de uso",
				use_name: "Nombre de uso",
				edition: "Edición",
				texture_id: "ID de textura",
				path_id: "ID de Ruta",
				resource_pack_path: "Ruta del Resource pack",
				mc_versions: "Versiones de Minecraft",
			},
		},
	},
	addons: {
		titles: {
			submit: "Enviar nuevo complemento",
			edit: "Editar complemento",
			submissions: "Envíos de complementos",
			details: "Detalles",
		},
		remove: {
			title: "Eliminar complemento",
			description: '"%s" se eliminará para siempre. Esto no se puede deshacer.',
		},
		general: {
			loading_addon: "Cargando complemento",
			no_submissions: "¡No has enviado ningún complemento!",
			go_to_addon: "Ver el listado público del complemento",
			rules: "Asegúrate de leer las reglas del complemento antes de enviar",
			title: "General",
			name: {
				label: "Nombre del complemento",
				hint: "Un nombre más corto es preferido.",
				rules: {
					name_required: "Se requiere un nombre.",
					name_too_big: "El nombre del complemento debe tener menos de %s caracteres.",
					name_too_small: "El nombre del complemento debe tener al menos %s caracteres.",
					name_unavailable: "¡Ese nombre ya está en uso!",
				},
			},
			slug: {
				label: "Slug de complemento",
				hint: "¡Cambiar esto romperá los enlaces antiguos!",
			},
			reason: {
				title: "Actualizar razón",
				text: "¡Por favor, sé lo más específico posible para facilitar la revisión de tu complemento!",
				required: "Se requiere una razón de actualización",
				bounds: "La razón de la actualización debe tener entre %s y %s caracteres",
			},
			authors: {
				label: "Seleccionar autores para el complemento",
				hint: "¡Cualquier autor puede modificar el complemento una vez que sea enviado! | Si no puedes encontrar a nadie en la lista, contacta con un administrador o desarrollador",
			},
		},
		info: {
			title: "Información",
			description: {
				placeholder: "Descripción del complemento",
				hint: "¡Puedes usar el marcado HTML para mejorar tu descripción!",
				rules: {
					description_required: "La descripción es obligatoria",
					description_too_big: "La descripción debe tener menos de %s caracteres",
					description_too_small: "La descripción debe tener al menos %s caracteres",
				},
			},
			embed_description: {
				label: "Incrustar descripción",
				hint: "Descripción visible al compartir las redes sociales del complemento",
				rules: {
					too_big: "La descripción al compartir debe tener menos de %s caracteres",
				},
			},
		},
		images: {
			title: "Capturas de pantalla",
			header: {
				labels: {
					drop: "Arrastra y suelta la imagen del encabezado o haz clic para subir",
					normal: "Imagen del encabezado",
					replace: "Reemplazar imagen del encabezado",
				},
				rules: {
					image_size:
						"¡El tamaño de la imagen debe ser inferior a %s KB! Use https://compressor.io/ para comprimirla.",
					image_ratio:
						"Ratio incorrecto: La imagen proporcionada no tiene una relación lateral 16:9.",
					image_required: "Se requiere una imagen de encabezado.",
					jpeg: "Imagen debe ser un JPEG con pérdida.",
					compress: "Puedes comprimir imágenes en https://compressor.io/",
				},
				status: {
					upload: "Imagen de portada subida correctamente",
					remove: "Imagen de portada eliminada correctamente",
				},
			},
			screenshots: {
				labels: {
					drop: "Arrastre o haga clic para seleccionar imágenes adicionales",
					normal: "Imágenes adicional(es)",
					replace: "Reemplazar imagen(es) adicionales",
				},
				rule: "Ratio incorrecto: Todas las imágenes con una relación lateral que no sea 16:9 han sido eliminadas.",
				status: {
					upload: "Captura de pantalla subida correctamente",
					remove: "Captura de pantalla eliminada correctamente",
				},
			},
		},
		compatibility: {
			title: "Compatibilidad",
			optifine: {
				label: "Requiere OptiFine",
			},
			editions: {
				label: "Requiere OptiFine",
			},
			packs: {
				label: "Ediciones compatibles",
			},
		},
		downloads: {
			title: "Descargas",
			add_group: "Agregar grupo de descargas",
			add_item: "Agregar descarga al grupo",
			remove_group: "Eliminar grupo de descargas y sus elementos",
			remove_item: "Eliminar descarga del grupo",
			name: {
				placeholder: "CurseForge, GitHub…",
				label: "Nombre",
				rules: {
					name_required: "Se requiere un nombre.",
					name_cannot_be_empty: "El nombre no puede estar vacío.",
				},
			},
			link: {
				placeholder: "https://www.ejemplo.com",
				label: "Enlace",
				rule: "La URL debe ser válida.",
			},
		},
	},
	review: {
		titles: {
			addons: "Revisar complementos",
			pending: "Aprobación pendiente",
			denied: "Denegado",
			approved: "Aprobado",
			archived: "Archivado",
		},
		reason_modal: {
			deny_title: "Rechazar complemento",
			archive_title: "Archivar complemento",
			warning: "¡Todos los autores del complemento pueden ver este motivo!",
			label: "Escribe un motivo…",
		},
		labels: {
			pending: "Actualmente no hay complementos pendientes!",
			denied: "Actualmente no hay complementos denegados!",
			archived: "Actualmente no hay complementos archivados!",
			approved: "¡Actualmente no hay complementos aprobados!",
			no_selection: "Ningún complemento seleccionado",
			search: "Buscar complementos",
			public_page: "Ver todos los complementos públicos",
		},
		addon: {
			titles: {
				last_updated: "Última actualización: %s",
				unknown_date: "Última actualización del complemento desconocida",
				compatibility: "Compatibilidad",
				author_singular: "Autor",
				author_plural: "Autores",
				description: "Descripción",
				download_singular: "Descarga",
				download_plural: "Descargas",
			},
			labels: {
				optifine: "Requiere OptiFine",
				approved_by: "Aprobado por %s",
				denied_by: "Denegado por %s",
				archived_by: "Archivado por %s",
				unknown_status: "Estado de revisión desconocido (%s)",
				reason: "Motivo",
				no_reason: "No se indicó ningún motivo",
			},
		},
	},
	posts: {
		titles: {
			list: "Todas las publicaciones",
			edit: "Editar publicación",
			new: "Crear nueva publicación",
		},
		status: {
			published: "Publicada el %s",
			draft: "Borrador",
		},
		loading: "Cargando publicación…",
		go_to_post: "Ver la versión publicada",
		general: {
			heading: "General",
			title: {
				label: "Título de la publicación",
				placeholder: "Faithful Smart Fridge: Alfa 1",
			},
			permalink: {
				label: "Enlace permanente",
				placeholder: "/faithfulsmartfridge/A1",
			},
			header_img: {
				label: "Imagen de encabezado (opcional)",
				hint: "Nota: Esto debe ser subido por separado",
				placeholder: "https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg",
			},
			date: {
				label: "Fecha de lanzamiento",
			},
			discontinued: {
				label: "Descontinuada",
				hint: "Si marcas esta opción, la publicación quedará marcada como descontinuada",
			},
			description: {
				placeholder: "Descripción del post",
				hint: "¡Puedes usar el marcado HTML para mejorar tu descripción!",
			},
		},
		download: {
			heading: "Descargas",
			add_category: "Agregar categoría de descarga",
			add_item_to_category: "Agregar descarga a la categoría",
			add_single_item: "Agregar descarga única",
			remove_category: "Eliminar categoría de descargas y sus elementos",
			remove_item_in_category: "Quitar descarga de la categoría",
			remove_single_item: "Eliminar descarga individual",
			category: "Nombre de la categoría de descarga",
			name: "Nombre de la Descarga",
			link: "Enlace de descarga",
			link_placeholder: "https://www.ejemplo.com",
		},
		changelog: {
			heading: "Registro de cambios",
			add_category: "Agregar categoría de registro de cambios",
			add_item: "Agregar elemento de registro de cambios",
			remove_category: "Eliminar categoría del registro de cambios",
			remove_item: "Eliminar elemento del registro de cambios",
			import_json: "Importar JSON",
			open_category: "Abrir categoría del registro de cambios",
			close_category: "Contraer categoría del registro de cambios",
			form_levels: {
				primary: "Categoría principal",
				secondary: "Categoría secundaria",
				item_category: "Categoría de artículo (autores)",
				item: "Artículo (autores)",
			},
		},
		changelog_generator: {
			heading: "Generar registro de cambios",
			date: "Fecha del último registro de cambios",
			pack: "Paquete para el registro de cambios",
			copy: "Copiar al portapapeles",
			categorize: "Clasificar automáticamente el registro de cambios por tipo (experimental)",
			categorize_warning:
				"¡La clasificación por tipo puede ser imprecisa debido a cómo se registran las contribuciones!",
			download: "Descargar registro de cambios",
			warning: "¡Por favor, revisa el registro de cambios manualmente antes de importarlo!",
		},
	},
	database: {
		search: "Buscar",
		anonymous: "Anónimo",
		nameless: "Sin Nombre",
		summary: "Resumen",
		confirm_deletion: "Confirmar eliminación",
		ask_deletion: "¿Desea eliminar %s (%d)?",
		contributions: {
			title: "Contribuciones",
			contributors: "Contribuyentes",
			add_contributions: "Agregar nuevas contribuciones",
			edit_contribution: "Editar contribución",
			delete_contribution: "Eliminar contribución",
			pack_filter: "Filtrar por pack",
			user_filter: "Usuarios",
			texture_filter: "Texturas",
			select_user: "Seleccionar usuario(s)",
			contribution_count_singular: "%d contribución",
			contribution_count_plural: "%d contribuciones",
			authorless: "No se han agregado autores",
			contribution_result: "Resultados de la contribución",
			search_contributions: "Buscar contribuciones",
			modal: {
				add_new_contribution: "Agregar nueva contribución",
				clone_contribution: "Clonar contribución seleccionada",
				one_contributor: "Seleccione al menos un contribuyente",
				id: "ID de contribución",
				id_hint: "¡Cambiar el ID de la contribución puede hacer que todo falle!",
				pack: "Paquete de recursos",
				texture_id: "ID de textura",
				texture_ids: "ID de textura",
				increment_texture: "Aumentar ID de textura",
				decrement_texture: "Disminuir ID de textura",
				id_field_errors: {
					one_required: "Se requiere al menos un ID de textura o un rango de ID",
					incorrect_value: "%VALUE% no es un ID de textura ni un rango de IDs válido",
				},
			},
		},
		users: {
			title: "Usuarios",
			role_filter: "Filtrar por rol",
			search_username: "Buscar nombre de usuario",
			user_result: "Resultados del usuario",
			modal: {
				add_user: "Agregar nuevo usuario",
				edit_user: "Editar usuario",
				delete_user: "Eliminar cuenta",
				id: "ID de Discord",
				id_hint:
					"Cambiar el ID de Discord actualizará todas las contribuciones y los complementos asociados a ese usuario",
				username: "Nombre de usuario",
				uuid: "UUID del perfil de Minecraft",
				roles: "Roles de usuario",
				anonymous: "Anónimo",
			},
		},
		textures: {
			title: "Texturas",
			add_texture: "Agregar nueva textura",
			add_multiple: "Agregar nuevas texturas",
			edit_texture: "Editar textura",
			texture_result: "Resultados de la textura",
			tag_filter: "Filtrar por etiqueta",
			search_texture: "Buscar el nombre de la textura",
			add_success: "Textura(s) agregadas con éxito",
			delete_modal: {
				title_texture: "Eliminar textura",
				title_use: "Eliminar uso",
				title_path: "Eliminar ruta",
				affected_uses: "Usos afectados",
				affected_paths: "Rutas afectadas",
				affected_contributions: "Contribuciones afectadas",
			},
			modal: {
				title: "Textura",
				subtitle: "Usos y rutas",
				tagless: "Sin etiquetas añadidas",
				copy_button: "Copiar los datos de las texturas como JSON",
				json_button: "Importar datos JSON",
				persist_button: "Conservar datos al guardar",
				copy_json_data: "Datos JSON copiados en el portapapeles",
				id_hint: "¡Cambiar un ID de pack puede romper todo!",
				id: "ID de textura",
				name: "Nombre de la textura",
				tags: "Etiquetas de textura",
				recompute_tag_list: "Regenerar etiquetas a partir de los datos de las rutas",
			},
			uses: {
				title: "Usos",
				singular: "Uso",
				plural: "Usos",
				add_use: "Agregar nuevo uso",
				edit_use: "Editar uso",
				add_edition_use: "Agregar uso automático de %EDITION%",
				no_use_found: "No se encontraron usos para esta textura",
				id_hint: "¡Cambiar un ID de pack puede romper todo!",
				id: "ID de uso",
				name: "Nombre de uso",
				edition: "Edición de uso",
			},
			paths: {
				title: "Rutas",
				singular: "Ruta",
				plural: "Rutas",
				add_path: "Agregar nueva ruta",
				edit_path: "Editar ruta",
				no_path_found: "No se encontraron rutas para este uso",
				id_hint: "¡Cambiar un ID de pack puede romper todo!",
				id: "ID de Ruta",
				name_hint: "La ruta debe comenzar en el directorio raíz (ej., assets/…)",
				name_prefill: "¡Ingrese esto primero para generar la mayoría de campos!",
				name: "Ruta",
				versions: "Versiones",
				mcmeta: "Animado",
			},
			merge_textures: {
				title: "Combinar texturas",
				warning: "¡Esto eliminará la textura de origen y no se puede deshacer!",
				source: "ID de la textura de origen",
				destination: "ID de la textura de destino",
				invalid_id: "ID de textura no válido",
			},
		},
		versions: {
			title: "Versiones",
			edition_filter: "Filtrar por edición",
			version_result: "Versiones encontradas",
			exists: "Ya existe una versión con ese nombre",
			path_count_singular: "%d ruta",
			path_count_plural: "%d rutas",
			no_paths: "No hay rutas asociadas",
			modal: {
				title: "Editar versión de Minecraft",
				name: "Nombre de la versión de Minecraft",
				edition: "Edición de Minecraft",
				warning: "¡Por favor, no olvides actualizar los nombres de todas las ramas de GitHub!",
			},
			add: {
				title: "Agregar nueva versión de Minecraft",
				success: "Versión agregada correctamente",
				new_edition: "Nueva edición de versión",
				template_version: "Versión base",
				new_version: "Nombre de la nueva versión",
			},
			delete: {
				title: "Eliminar versión de Minecraft",
				description: "¿Quieres eliminar la versión %VERSION% de la edición %EDITION%?",
				no_affected_paths: "No se verá afectada ninguna ruta",
				affected_paths_singular: "Se verá afectada %d ruta.",
				affected_paths_plural: "Se verán afectadas %d rutas.",
			},
		},
		packs: {
			title: "Packs",
			tag_filter: "Filtrar por etiqueta",
			pack_result: "Resultados del pack",
			modal: {
				add_pack: "Agregar nuevo pack",
				edit_pack: "Editar pack",
				delete_pack: "Eliminar paquete",
				id: "ID del pack",
				id_creation_hint:
					"El ID de paquete se puede especificar manualmente o generar automáticamente",
				id_editing_hint: "¡Cambiar un ID de pack puede romper todo!",
				name: "Nombre del pack",
				tags: "Etiquetas del pack",
				resolution: "Resolución del pack",
				color: "Color del paquete",
				logo: "URL del logo del pack",
				github: {
					title: "GitHub",
					title_hint: "Puedes dejar una edición en blanco si todavía no tiene soporte",
					length_notice: "Debe haber al menos un repositorio de GitHub",
					organization: "Organización",
					repository: "Repositorio",
				},
				delete_hint:
					"Eliminar un paquete lo quitará de la galería de texturas y de los bots de Discord, pero no afectará sus repositorios de GitHub.",
			},
			submissions: {
				title: "Información de envío",
				delete_submission: "Eliminar información de envíos",
				add_submission: "Agregar información de envío",
				edit_submission: "Editar información de envío",
				reference_pack: "Pack de referencia",
				reference_hint: "Paquete con el que se comparan los envíos en sus embeds",
				contributor_role: "ID de rol de contribuyente",
				time_to_results: "Tiempo hasta los resultados",
				time_hint: "El tiempo de espera se indica en días",
				channels: {
					title: "Canales de Discord",
					title_hint:
						"Activa el modo desarrollador y haz clic derecho en un canal para obtener su ID",
					submit: "Canal de envío",
					results: "Canal de resultados",
				},
				delete_warning: "¡Esto eliminará %d contribuciones!",
			},
		},
		settings: {
			title: "Editar configuración global",
		},
	},
};
