export default {
 credits: 'Juknum',
 global: {
  name: 'Faithful',
  login: 'Se connecter',
  logout: 'Déconnexion',
  success_message: 'Terminé avec succès',
  loading: 'Chargement, veuillez patienter…',
  no_results: 'Aucun résultat trouvé',
  nyi: "N'a pas encore été implémenté.",
  invalid_url: "Cette URL n'est pas valide",
  navbar: {
   labels: {
    sidebar: 'Activer/désactiver la barre latérale',
    theme: 'Montrer/Masquer le menu déroulant des thèmes',
    translations: 'Montrer/Masquer le menu déroulant de traduction',
    user: 'Connecté en tant que %s',
   },
   translations: {
    title: 'Traductions',
    crowdin: 'Aidez à traduire',
   },
   profile: {
    view: 'Votre profil',
    main_site: 'Site web de Faithful',
    manage: 'Gérer les comptes',
    copy: "Copier l'ID de l'utilisateur",
    copied: "ID de l'utilisateur copié",
   },
  },
  connection: {
   logo: 'Logo Faithful',
   description: 'Problème de connexion ?',
   contact: 'Contactez-nous',
   status: 'Status Faithful',
  },
  footer: {
   credits: 'Le site web a été crée en utilisant le framework de composants %Vuetify%.',
   source: 'Code source %here%!',
   copyright: '© %d Pack de ressources Faithful',
  },
  themes: {
   notification: 'Thème système changé en %s',
   dark_sidebar: 'Barre latérale sombre',
   title: 'Thèmes',
   options: {
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
   },
  },
  btn: {
   add: 'Ajouter',
   submit: 'Soumettre',
   submit_for_review: 'Soumettre pour vérification',
   submit_and_approve: 'Soumettre et approuver',
   cancel: 'Annuler',
   close: 'Fermer',
   copy: 'Copier',
   save: 'Sauvegarder',
   edit: 'Éditer',
   delete: 'Supprimer',
   ok: 'OK',
   yes: 'Oui',
   deny: 'Refuser',
   confirm: 'Confirmer',
   approve: 'Approuver',
   archive: 'Archiver',
   load_more: 'Charger plus',
   reset: 'Réinitialiser le formulaire',
   report: 'Signaler',
   publish: 'Publier',
   save_draft: 'Enregistrer comme brouillon',
  },
  tabs: {
   general: {
    title: 'Général',
    subtabs: {
     dashboard: 'Dashboard',
     profile: 'Profil',
     gallery: 'Galerie',
    },
   },
   addons: {
    title: 'Add-on',
    subtabs: {
     new: 'Nouvel add-on',
     submissions: 'Mes add-ons',
     review: 'Vérification',
    },
   },
   posts: {
    title: 'Posts',
    subtabs: {
     create: 'Créer une publication',
     all: 'Tous les posts',
    },
   },
   database: {
    title: 'Database',
    subtabs: {
     contributions: 'Contributions',
     users: 'Utilisateurs',
     textures: 'Textures',
     versions: 'Versions',
     packs: 'Packs',
     settings: 'Paramètres',
    },
   },
  },
  json_editor: {
   import_data: 'Importer des données JSON',
   parse_json: 'Convertir le JSON en données',
  },
  datepicker: {
   year: 'Année',
   month: 'Mois',
   day: 'Jour',
  },
  tabbed_text_field: {
   write: 'Éditer',
   preview: 'Aperçu',
   empty: 'Rien à prévisualiser',
  },
  drop_zone: {
   standby_singular: 'Déposez un fichier ou cliquez pour en sélectionner',
   standby_plural: 'Déposez des fichiers ou cliquez pour en sélectionner',
   dragging_singular: 'Relâcher pour charger le fichier',
   dragging_plural: 'Relâcher pour charger les fichiers',
  },
  account_manager: {
   title: 'Gestionnaire de compte',
   active_account: 'Compte actif',
   add_account: 'Ajouter un nouveau compte',
   switch_accounts: 'Basculer de compte',
   avatar_alt_text: 'Avatar de %s',
  },
  emitting_image: {
   fullscreen: 'Ouvrir en plein écran',
   delete: 'Supprimer l’image',
  },
 },
 missing_page: {
  title: "Êtes-vous perdus dans l'end ?",
  description: "Malheureusement, la page que vous avez demandée n'existe pas !",
  main_page: "Essayez de vérifier votre orthographe ou d'aller sur la %main page% pour trouver ce que vous cherchez.",
 },
 dashboard: {
  welcome: 'Bienvenue dans Faithful Studio !',
  welcome_user: 'Bienvenue %USER% !',
  totals: {
   authors: 'auteurs',
   contributions: 'contributions',
   last_year: "contributions de l'année dernière",
   last_month: 'contributions ce mois',
   last_week: 'contributions cette semaine',
   last_day: 'contributions dans les 48 dernières heures',
  },
  titles: {
   profile: 'Votre profil',
   textures: 'Textures',
   addons: 'Add-ons',
   contribution_stats: 'Contributions',
   contribution_activity: 'Activité de contribution',
  },
  profile: {
   login_notice: 'Connectez-vous pour accéder à plus de fonctionnalités !',
   login_button: 'Se connecter via Discord',
  },
  addons: {
   submissions: 'Mes add-ons',
   upload: 'Mettre en ligne',
  },
  textures: {
   total: 'Textures',
   versions: 'Versions',
  },
  locale: {
   on: 'le',
   less: 'Moins',
   more: 'Plus',
  },
 },
 profile: {
  title: 'Profil',
  public_profile: 'Voir le profil public',
  general: {
   title: 'Général',
   username: {
    label: 'Pseudonyme',
    hint:
     'Votre pseudonyme sera affiché et utilisé sur le site pour les contributions, les add-ons et bien plus encore…',
    rules: {
     min: 'Le pseudo doit comporter plus de %d caractères',
     max: 'Votre pseudo doit faire moins de %d caractères',
    },
   },
   uuid: {
    label: 'UUID du profil Minecraft',
    hint: 'Votre skin sera sur votre profil et sur les add-ons',
    skin_alt_text: 'Skin Minecraft',
    rules: {
     length: "L'UUID doit faire exactement 36 caractères de long",
    },
   },
   bio: {
    label: 'Bio',
    placeholder: 'Bio',
    hint: 'Vous pouvez utiliser le formatage Markdown pour styliser votre bio !',
    rules: {
     length: 'Votre bio doit faire moins de %d caractères',
    },
   },
   anonymous: {
    label: 'Anonyme',
    hint:
     "Désactive la page de profil et masque le nom d'utilisateur et le thème Minecraft dans la galerie de textures. Le nom d'utilisateur sera toujours accessible dans les soumissions de textures à des fins de crédit, mais n'apparaîtra nulle part ailleurs.",
   },
  },
  social: {
   title: 'Réseaux Sociaux',
   add: 'Ajouter un réseau social',
   remove: 'Supprimer un réseau social',
   type: {
    label: 'Type de réseau social',
    rules: {
     exists: 'Le type de réseau social est requis',
     valid: 'Le type de réseau social doit être valide',
    },
   },
   link: {
    label: 'Lien vers le profil social',
    placeholder: 'https://www.exemple.com/',
    rules: {
     valid: "L'URL doit être valide.",
    },
   },
  },
  save_changes: 'Sauvegarder les modifications',
  delete: {
   title: 'Supprimer le compte',
   btn: 'Supprimer le compte',
   warning: 'Ce processus est irréversible !',
   addons: {
    title_singular: 'Cela affectera %d add-on',
    title_plural: 'Cela affectera %d add-ons',
    deleted: 'Supprimé',
    transferred: "Transféré à d'autres auteurs",
   },
  },
 },
 gallery: {
  title: 'Galerie',
  max_items_per_row: "Maximum d'items par ligne",
  stretched_switcher: 'Vue en pleine largeur',
  animated_switcher: 'Jouer les animations',
  share: 'Partager la texture',
  to_top: 'Revenir au début de la page',
  share_link_copied_to_clipboard: 'Lien copié dans le presse-papiers',
  authors_copied_to_clipboard: 'Les auteurs ayant soumis la texture ont été copiés dans le presse-papiers',
  loading_message: 'Chargement des résultats de la galerie…',
  error_message: {
   texture_not_done: "La texture n'a pas été faite !",
   user_anonymous: 'Anonyme',
   user_not_found: 'Utilisateur Inconnu',
   contribution_not_found: 'Aucune contribution trouvée dans la base de donnée!',
   search_failed: 'La recherche a échoué',
  },
  category: {
   pack: 'Pack',
   edition: 'Édition',
   mc_version: 'Versions Minecraft',
   tag: 'Tag',
   search: 'Rechercher',
  },
  sort: {
   name_asc: 'Nom (A → Z)',
   name_desc: 'Nom (Z → A)',
   id_asc: 'ID de la texture (plus petit → plus grand)',
   id_desc: 'ID de la texture (plus grand → plus petit)',
   contrib_desc: 'Contribution récente',
  },
  tooltip: {
   modded: 'Texture moddée',
   mojang: 'Mojang Studios',
   ignored: 'Texture ignorée',
  },
  all: 'Tout',
  latest: 'Dernière',
  clear_cache: 'Vider le cache de la galerie',
  result_stats_singular: '%COUNT% texture trouvée en %SECONDS% secondes',
  result_stats_plural: '%COUNT% textures trouvées en %SECONDS% secondes',
  modal: {
   no_contributions: 'Aucune contribution trouvée',
   image_alt_text: 'Texture %NAME% pour le pack %PACK%',
   loading: 'Chargement de la texture…',
   ignored: "Cette texture a été ignorée et peut ne pas être mise à l'échelle pour tous les projets !",
   tabs: {
    information: 'Information',
    authors: 'Auteurs',
    animation: 'Animation',
   },
   info: {
    texture: 'Texture',
    uses: 'Utilisations',
    paths: 'Chemins',
   },
   animation: {
    texture_mcmeta: 'MCMETA',
   },
   data: {
    contribution_id: 'ID de contribution',
    date: 'Date',
    authors: 'Auteur(s)',
    id: 'ID',
    name: 'Nom',
    tags: 'Tags',
    use_id: "ID de l'utilisation",
    use_name: "Nom de l'utilisation",
    edition: 'Édition',
    texture_id: 'ID de la texture',
    path_id: 'ID du chemin',
    resource_pack_path: 'Chemin dans le Resource Pack',
    mc_versions: 'Version(s) Minecraft',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Soumettre un nouvel Add-on',
   edit: "Éditer l'addon",
   submissions: 'Mes Add-ons',
   details: 'Détails',
  },
  remove: {
   title: "Supprimer l'add-on",
   description: '«%s» sera supprimé pour toujours. Cette action ne peut pas être annulée.',
  },
  general: {
   loading_addon: "Chargement de l'addon",
   no_submissions: "Vous n'avez soumis aucun add-on !",
   go_to_addon: 'Voir la liste publique des add-ons',
   rules: "Assurez-vous que l'add-on suit les règles décrites dans la documentation",
   title: 'Général',
   name: {
    label: "Nom de l'add-on",
    hint: 'Un nom plus court est préférable',
    rules: {
     name_required: 'Le nom est requis.',
     name_too_big: 'Le nom doit faire moins que %s caractères.',
     name_too_small: 'Le nom doit faire au moins %s caractères de long',
     name_unavailable: 'Ce nom est déjà pris !',
    },
   },
   slug: {
    label: "Identifiant de l'add-on",
    hint: 'Changer ceci va casser les anciens liens !',
   },
   reason: {
    title: 'Raison de la modification',
    text: 'Soyez aussi précis que possible pour faciliter la révision de votre add-on !',
    required: 'Une raison de mise à jour est requise',
    bounds: 'La raison de la mise à jour doit contenir entre %s et %s caractères',
   },
   authors: {
    label: 'Sélectionner un ou des auteurs pour cet add-on',
    hint:
     "N'importe quel auteur peut modifier l'add-on une fois soumis ! | Si vous ne trouvez pas quelqu'un dans la liste, contactez un Administrateur/Développeur",
   },
  },
  info: {
   title: 'Information',
   description: {
    placeholder: "Description de l'add-on",
    hint: 'Vous pouvez utiliser du formatage Markdown pour styliser votre description !',
    rules: {
     description_required: 'La description est requise',
     description_too_big: 'La description doit comporter moins de %s caractères',
     description_too_small: 'La description doit comporter au moins %s caractères',
    },
   },
   embed_description: {
    label: "Description de l'intégration",
    hint: "Description vue lors du partage de l'add-on sur les réseaux sociaux",
    rules: {
     too_big: "La description de l'intégration doit comporter moins de %s caractères",
    },
   },
  },
  images: {
   title: "Captures d'écran",
   header: {
    labels: {
     drop: "Glissez l'image d'en-tête ou cliquez pour sélectionner",
     normal: "Image d'en-tête",
     replace: "Changer l'image d'en-tête",
    },
    rules: {
     image_size: "L'image doit faire moins de %s KB! Utilisez https://compressor.io/ pour le compresser.",
     image_ratio: "Ratio incorrect: L'image envoyée ne possède pas un ratio en 16/9.",
     image_required: "Une image d'en-tête est requise.",
     jpeg: "L'image doit être un JPEG avec perte",
     compress: 'Vous pouvez compresser les images en utilisant https://compressor.io/',
    },
    status: {
     upload: "Image d'en-tête téléchargée avec succès",
     remove: "Image d'en-tête supprimée avec succès",
    },
   },
   screenshots: {
    labels: {
     drop: 'Glissez ou cliquez pour ajouter des images additionnelles',
     normal: 'Image(s) additionnelles',
     replace: 'Remplacer les images additionnelles',
    },
    rule: "Ratio incorrect: Les images qui n'ont pas un ratio en 16/9 ont été enlevées.",
    status: {
     upload: "Capture d'écran téléchargée avec succès",
     remove: "Capture d'écran supprimée avec succès",
    },
   },
  },
  compatibility: {
   title: 'Compatibilité',
   optifine: {
    label: 'Requière OptiFine',
   },
   editions: {
    label: 'Éditions prises en charge',
   },
   packs: {
    label: 'Packs pris en charge',
   },
  },
  downloads: {
   title: 'Téléchargements',
   add_group: 'Ajouter un groupe de téléchargement',
   add_item: 'Ajouter un téléchargement au groupe',
   remove_group: 'Supprimer le groupe de téléchargement et les éléments',
   remove_item: 'Supprimer le téléchargement du groupe',
   name: {
    placeholder: 'CurseForge, GitHub…',
    label: 'Nom',
    rules: {
     name_required: 'Un nom est requis.',
     name_cannot_be_empty: 'Le nom ne peut être vide.',
    },
   },
   link: {
    placeholder: 'https://www.exemple.com/',
    label: 'Lien',
    rule: "L'URL doit être valide.",
   },
  },
 },
 review: {
  titles: {
   addons: 'Vérifier les Add-ons',
   pending: 'En attente de validation',
   denied: 'Refusé(s)',
   approved: 'Accepté(s)',
   archived: 'Archivé(s)',
  },
  reason_modal: {
   deny_title: "Refuser l'add-on",
   archive_title: "Archiver l'add-on",
   warning: 'Tous les auteurs des add-ons peuvent voir cette raison !',
   label: 'Écrivez une raison…',
  },
  labels: {
   pending: "Il n'y a actuellement aucun add-on en attente !",
   denied: "Il n'y a actuellement aucun add-on refusé !",
   archived: "Il n'y a actuellement aucun add-on archivé !",
   approved: "Il n'y a actuellement aucun add-on approuvé !",
   no_selection: 'Aucun add-on sélectionné',
   search: 'Rechercher des add-ons',
   public_page: 'Aller à tous les add-ons publics',
  },
  addon: {
   titles: {
    last_updated: 'Dernière MàJ : %s',
    unknown_date: "Dernière mise à jour de l'add-on inconnue",
    compatibility: 'Compatibilité',
    author_singular: 'Auteur',
    author_plural: 'Auteur(s)',
    description: 'Description',
    download_singular: 'Téléchargement',
    download_plural: 'Téléchargements',
   },
   labels: {
    optifine: 'Requière OptiFine',
    approved_by: 'Approuvé par %s',
    denied_by: 'Refusé par %s',
    archived_by: 'Archivé par %s',
    unknown_status: 'Statut de la revue inconnu (%s)',
    reason: 'Raison',
    no_reason: 'Aucune raison fournie',
   },
  },
 },
 posts: {
  titles: {
   list: 'Tous les posts',
   edit: 'Éditer le post',
   new: 'Créer un nouveau post',
  },
  status: {
   published: 'Publié le %s',
   draft: 'Brouillon',
  },
  loading: 'Chargement du post…',
  go_to_post: 'Voir le post publié',
  general: {
   heading: 'Général',
   title: {
    label: 'Titre du post',
    placeholder: 'Rafraîchisseur intelligent Faithful: Alpha 1',
   },
   permalink: {
    label: 'Lien permanent',
    placeholder: '/fr/fidfulsmartfridge/A1',
   },
   header_img: {
    label: "Image d'en-tête (facultatif)",
    hint: 'Remarque : ceci doit être téléchargé séparément',
    placeholder: 'https://database.faithfulpack.net/images/web/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Date de publication du post',
   },
   discontinued: {
    label: 'Obsolète',
    hint: 'Si coché, le message sera marqué comme obsolète',
   },
   description: {
    placeholder: 'Description du post',
    hint: 'Vous pouvez utiliser du formatage Markdown pour styliser votre description !',
   },
  },
  download: {
   heading: 'Téléchargements',
   add_category: 'Ajouter une catégorie de téléchargement',
   add_item_to_category: 'Ajouter un téléchargement à la catégorie',
   add_single_item: 'Ajouter un téléchargement unique',
   remove_category: 'Supprimer la catégorie de téléchargement et les éléments',
   remove_item_in_category: 'Retirer le téléchargement de la catégorie',
   remove_single_item: 'Supprimer le téléchargement unique',
   category: 'Nom de la catégorie de téléchargement',
   name: 'Nom du téléchargement',
   link: 'Lien de téléchargement',
   link_placeholder: 'https://www.exemple.com/',
  },
  changelog: {
   heading: 'Journal des modifications',
   add_category: 'Ajouter une catégorie au journal des modifications',
   add_item: 'Ajouter un élément au journal des modifications',
   remove_category: 'Supprimer la catégorie du journal des modifications',
   remove_item: "Supprimer l'élément du journal des modifications",
   import_json: 'Importer du JSON',
   open_category: 'Ouvrir la catégorie du journal des modifications',
   close_category: 'Réduire la catégorie du journal des modifications',
   form_levels: {
    primary: 'Catégorie Principale',
    secondary: 'Catégorie secondaire',
    item_category: "Catégorie d'éléments (Auteur·e·s)",
    item: 'Élément (Auteur·e·s)',
   },
  },
  changelog_generator: {
   heading: 'Générer le journal des modifications',
   date: 'Date depuis le dernier journal des modifications',
   pack: 'Pack du journal des modifications',
   copy: 'Copier dans le presse-papier',
   categorize: 'Catégoriser automatiquement le journal des modifications par type (expérimental)',
   categorize_warning:
    'La catégorisation de types peut être inexacte en raison de la manière dont les contributions se suivent !',
   download: 'Télécharger le journal des modifications',
   warning: "Veuillez vérifier manuellement le journal des modifications avant de l'importer!",
  },
 },
 database: {
  search: 'Rechercher',
  anonymous: 'Anonyme',
  nameless: 'Sans nom',
  summary: 'Résumé',
  confirm_deletion: 'Confirmer la suppression',
  ask_deletion: 'Voulez-vous supprimer %s (%d)?',
  contributions: {
   title: 'Contributions',
   contributors: 'Contributeurs',
   add_contributions: 'Ajouter des nouvelles contributions',
   edit_contribution: 'Modifier la contribution',
   delete_contribution: 'Supprimer la contribution',
   pack_filter: 'Filtrer par pack',
   user_filter: 'Utilisateurs',
   texture_filter: 'Textures',
   select_user: 'Choisir des utilisateurs',
   contribution_count_singular: '%d contribution',
   contribution_count_plural: '%d contributions',
   authorless: 'Aucun auteur·e ajouté·e',
   contribution_result: 'Résultats de contributions',
   search_contributions: 'Rechercher des contributions',
   modal: {
    add_new_contribution: 'Ajouter une nouvelle contribution',
    clone_contribution: 'Dupliquer la contribution sélectionnée',
    one_contributor: 'Veuillez choisir au moins un utilisateur',
    id: 'ID de contribution',
    id_hint: "Changer l'ID de la contribution peut tout briser !",
    pack: 'Pack de ressources',
    texture_id: 'ID de la texture',
    texture_ids: 'ID de textures',
    increment_texture: "Incrémenter l'ID de texture",
    decrement_texture: "Décrémenter l'ID de texture",
    id_field_errors: {
     one_required: "Au moins un ID ou une plage d'IDs de textures requis",
     incorrect_value: "Intervalle d'ID ou ID %VALUE% de texture incorrecte",
    },
   },
  },
  users: {
   title: 'Utilisateurs',
   role_filter: "Sélectionnez le role de l'utilisateur",
   search_username: 'Rechercher un pseudonyme',
   user_result: "Résultats d'utilisateurs",
   modal: {
    add_user: 'Ajouter un contributeur',
    edit_user: 'Éditer le contributeur',
    delete_user: 'Supprimer le compte',
    id: 'ID Discord',
    id_hint: "Changer l'ID de Discord va mettre à jour toutes les contributions et tous les add-ons reliés",
    username: 'Pseudonyme',
    uuid: 'UUID du profil Minecraft',
    roles: "Roles de l'utilisateur",
    anonymous: 'Anonyme',
   },
  },
  textures: {
   title: 'Textures',
   add_texture: 'Ajouter une texture',
   add_multiple: 'Ajouter des textures',
   edit_texture: 'Éditer la texture',
   texture_result: 'Résultats des textures',
   tag_filter: 'Filtrer par tag',
   search_texture: 'Rechercher un nom de texture',
   add_success: 'Textures ajoutées avec succès',
   delete_modal: {
    title_texture: 'Supprimer la texture',
    title_use: "Supprimer l'utilisation",
    title_path: "Supprimer le chemin d'accès",
    affected_uses: 'Utilisations affectées',
    affected_paths: "Chemins d'accès affectés",
    affected_contributions: 'Contributions affectées',
   },
   modal: {
    title: 'Texture',
    subtitle: "Utilisations et chemins d'accès",
    tagless: 'Aucun tag ajouté',
    copy_button: 'Copier les données de textures en JSON',
    json_button: 'Importer des données JSON',
    persist_button: 'Persister à enregistrer',
    copy_json_data: 'Données JSON copiées dans le presse-papiers',
    id_hint: "Changer l'ID de la texture peut tout casser",
    id: 'ID de la texture',
    name: 'Nom de la texture',
    tags: 'Type de la texture',
    recompute_tag_list: "Régénérer les tags en utilisant les données de chemin d'accès",
   },
   uses: {
    title: 'Utilisations',
    singular: 'Utilisation',
    plural: 'Utilisations',
    add_use: 'Ajouter une utilisation',
    edit_use: "Éditer l'utilisation",
    add_edition_use: "Ajouter l'utilisation automatique de %EDITION%",
    no_use_found: 'Aucune utilisation trouvée pour cette texture',
    id_hint: "Changer l'ID de l'utilisation peut tout casser",
    id: "ID de l'utilisation",
    name: "Nom de l'utilisation",
    edition: "Edition de l'utilisation",
   },
   paths: {
    title: "Chemins d'accès",
    singular: "Chemin d'accès",
    plural: "Chemins d'accès",
    add_path: 'Ajouter un chemin',
    edit_path: 'Éditer le chemin',
    no_path_found: "Aucun chemin d'accès trouvé pour cette utilisation",
    id_hint: "Changer l'ID du chemin peut tout casser",
    id: 'ID du chemin',
    name_hint: "Le chemin d'accès doit commencer à partir du répertoire racine (ex. : assets/...)",
    name_prefill: 'Remplissez ceci en premier pour générer le plus dans le formulaire !',
    name: "Chemin d'accès",
    versions: 'Versions',
    mcmeta: 'Animée',
   },
   merge_textures: {
    title: 'Fusionner des textures',
    warning: 'Cela va supprimer la texture source et ne pourra pas être annulé !',
    source: 'ID de texture source',
    destination: 'ID de texture de destination',
    invalid_id: 'ID de texture invalide',
   },
  },
  versions: {
   title: 'Versions',
   edition_filter: 'Filtrer par édition',
   version_result: 'Résultats de version',
   exists: 'Le nom de version existe déjà',
   path_count_singular: "Chemin d'accès %d",
   path_count_plural: "Chemins d'accès %d",
   no_paths: "Aucun chemin d'accès associé",
   modal: {
    title: 'Modifier une version de Minecraft',
    name: 'Nom de version Minecraft',
    edition: 'Édition de Minecraft',
    warning: "N'oubliez pas de mettre à jour tous les noms de branches de GitHub !",
   },
   add: {
    title: 'Ajouter une nouvelle version Minecraft',
    success: 'Version ajoutée avec succès',
    new_edition: 'Édition à laquelle ajouter une version',
    template_version: 'Version du modèle',
    new_version: 'Nom de la nouvelle version',
   },
   delete: {
    title: 'Supprimer la version de Minecraft',
    description: "Voulez-vous supprimer la version %VERSION% pour l'édition %EDITION% ?",
    no_affected_paths: "Aucuns chemins d'accès ne seront affectés",
    affected_paths_singular: "Le chemin d'accès %d sera affecté.",
    affected_paths_plural: "%d chemins d'accès seront affectés.",
   },
  },
  packs: {
   title: 'Packs',
   tag_filter: 'Filtrer par tag',
   pack_result: 'Résultats de packs',
   modal: {
    add_pack: 'Ajouter un nouveau pack',
    edit_pack: 'Modifier le pack',
    delete_pack: 'Supprimer le pack',
    id: 'ID du pack',
    id_creation_hint: 'Un ID de pack peut être modifié manuellement ou généré automatiquement',
    id_editing_hint: 'Changer un ID de pack peut tout casser !',
    name: 'Nom du pack',
    tags: 'Tags du pack',
    resolution: 'Résolution du pack',
    color: 'Couleur du pack',
    logo: 'URL du logo du pack',
    github: {
     title: 'GitHub',
     title_hint: 'Une édition pas encore supportée peut être laissée vide',
     length_notice: 'Au moins un dépôt GitHub doit être présent',
     organization: 'Organisation',
     repository: 'Dépôt distant',
    },
    delete_hint:
     "Supprimer un pack va l'enlever de la galerie des textures et des bots de Discord, mais n'affectera pas ses dépôts GitHub.",
   },
   submissions: {
    title: 'Informations de la soumission',
    delete_submission: 'Supprimer les informations de soumission',
    add_submission: 'Ajouter des informations de soumission',
    edit_submission: 'Modifier les informations de soumission',
    reference_pack: 'Pack de référence',
    reference_hint: "Pack auquel comparer en soumission d'intégrations",
    contributor_role: 'ID du rôle du contributeur',
    time_to_results: 'Temps avant les résultats',
    time_hint: 'Les délais sont mesurés en jours',
    channels: {
     title: 'Canaux Discord',
     title_hint: 'Activez le Mode développeur et faites un clic droit sur un canal pour obtenir les ID de canaux',
     submit: 'Canal de soumission',
     results: 'Chaîne de résultats',
    },
    delete_warning: 'Ceci va supprimer %d contributions !',
   },
  },
  settings: {
   title: 'Modifier les paramètres généraux',
  },
 },
};
