export default {
	credits: ["pure_shadow."],
	global: {
		name: "Faithful",
		login: "Entrar",
		logout: "Sair",
		success_message: "Concluído com sucesso",
		loading: "Carregando, por favor aguarde…",
		no_results: "Nenhum resultado encontrado",
		nyi: "Não implementado ainda.",
		invalid_url: "Esta URL não é válida",
		navbar: {
			labels: {
				sidebar: "Ativar/Desativar barra lateral",
				theme: "Ativar/Desativar menu suspenso de temas",
				translations: "Ativar/Desativar menu suspenso de traduções",
				user: "Conectado como %s",
			},
			translations: {
				title: "Traduções",
				crowdin: "Ajude a traduzir",
			},
			profile: {
				view: "Seu perfil",
				main_site: "Site Faithful",
				manage: "Gerenciar contas",
				copy: "Copiar ID de usuário",
				copied: "ID de usuário copiado para a área de transferência",
			},
		},
		connection: {
			logo: "Logo Faithful",
			description: "Problemas com conexão?",
			contact: "Fale conosco",
			status: "Status Faithful",
		},
		footer: {
			credits: "Este site foi feito usando o framework de componente %Vuetify%.",
			source: "Veja o código-fonte %here%!",
			copyright: "© %d Faithful Resource Pack",
		},
		themes: {
			notification: "Tema do sistema alterado para %s",
			dark_sidebar: "Barra lateral escura",
			title: "Temas",
			options: {
				light: "Claro",
				dark: "Escuro",
				system: "Sistema",
			},
		},
		btn: {
			add: "Adicionar",
			submit: "Enviar",
			submit_for_review: "Enviar para revisão",
			submit_and_approve: "Enviar e aprovar",
			cancel: "Cancelar",
			close: "Fechar",
			save: "Salvar",
			edit: "Editar",
			delete: "Excluir",
			ok: "OK",
			yes: "Sim",
			deny: "Negar",
			approve: "Aprovar",
			archive: "Arquivar",
			load_more: "Carregar mais",
			reset: "Redefinir formulário",
			confirm: "Confirmar",
			publish: "Publicar",
			save_draft: "Salvar como rascunho",
		},
		tabs: {
			general: {
				title: "Geral",
				subtabs: {
					dashboard: "Painel",
					profile: "Perfil",
					gallery: "Galeria",
				},
			},
			addons: {
				title: "Addons",
				subtabs: {
					new: "Novo addon",
					submissions: "Envios",
					review: "Revisar",
				},
			},
			posts: {
				title: "Publicações",
				subtabs: {
					create: "Criar publicação",
					all: "Todas as publicações",
				},
			},
			database: {
				title: "Banco de dados",
				subtabs: {
					contributions: "Contribuições",
					users: "Usuários",
					textures: "Texturas",
					versions: "Versões",
					packs: "Pacotes",
					settings: "Configurações",
				},
			},
		},
		json_editor: {
			import_data: "Importar dados em JSON",
			parse_json: "Analisar JSON para dados",
		},
		datepicker: {
			year: "Ano",
			month: "Mês",
			day: "Dia",
		},
		tabbed_text_field: {
			write: "Escreva",
			preview: "Prévia",
			empty: "Nenhuma prévia",
		},
		drop_zone: {
			standby_singular: "Arraste o arquivo ou clique para selecionar",
			standby_plural: "Arraste os arquivos ou clique para selecionar",
			dragging_singular: "Solte para enviar o arquivo",
			dragging_plural: "Solte para enviar os arquivos",
		},
		account_manager: {
			title: "Gerenciador de contas",
			active_account: "Ativar conta",
			add_account: "Adicionar nova conta",
			switch_accounts: "Trocar para a conta",
			avatar_alt_text: "Avatar de %s",
		},
		emitting_image: {
			fullscreen: "Abrir em tela cheia",
			delete: "Remover imagem",
		},
	},
	missing_page: {
		title: "Você está perdido no Fim?",
		description: "Infelizmente, a página que você solicitou não existe!",
		main_page:
			"Tente verificar a ortografia ou ir para a página %main % para encontrar o que estava procurando.",
	},
	dashboard: {
		welcome: "Bem-vindo ao Faithful Studio!",
		welcome_user: "Bem-vindo, %USER%!",
		totals: {
			authors: "autores",
			contributions: "contribuições",
			last_year: "contribuições no último ano",
			last_month: "contribuições no último mês",
			last_week: "contribuições na última semana",
			last_day: "contribuições nas últimas 48 horas",
		},
		titles: {
			profile: "Perfil",
			textures: "Texturas",
			addons: "Add-ons",
			contribution_stats: "Contribuições",
			contribution_activity: "Atividade de contribuição",
		},
		profile: {
			login_notice: "Faça login para acessar mais recursos!",
			login_button: "Entrar com Discord",
		},
		addons: {
			submissions: "Envios",
			upload: "Enviar",
		},
		textures: {
			total: "Texturas",
			versions: "Versões",
		},
		locale: {
			on: "ligado",
			less: "Menos",
			more: "Mais",
		},
	},
	profile: {
		title: "Perfil",
		public_profile: "Ir para perfil público",
		general: {
			title: "Geral",
			username: {
				label: "Nome de usuário",
				hint: "Seu nome de usuário será mostrado e usado no Website em contribuições, addons, etc.",
				rules: {
					min: "O nome de usuário deve ter mais de %d caracteres",
					max: "O nome de usuário deve ter menos de %d caracteres",
				},
			},
			uuid: {
				label: "UUID do perfil do Minecraft",
				hint: "Sua skin será exibida em seu perfil e nas páginas de addons",
				skin_alt_text: "Skin do Minecraft",
				rules: {
					length: "UUID deve ter exatamente 36 caracteres",
				},
			},
			bio: {
				label: "Bio",
				placeholder: "Bio",
				hint: "Você pode usar formatação Markdown para estilizar sua bio!",
				rules: {
					length: "A bio deve ter menos de %d caracteres",
				},
			},
			anonymous: {
				label: "Anônimo",
				hint: "Desativar página de perfil e ocultar nome de usuário e skin do Minecraft na galeria de texturas. Nomes de usuário ainda estarão acessíveis em envios de texturas para propósitos de crédito, mas não aparecerão em nenhum outro lugar.",
			},
		},
		social: {
			title: "Links sociais",
			add: "Adicionar rede social",
			remove: "Remover rede social",
			type: {
				label: "Tipo de rede social",
				rules: {
					exists: "Um tipo de rede social é necessário",
					valid: "O tipo de rede social deve ser válido",
				},
			},
			link: {
				label: "Link para o perfil de rede social",
				placeholder: "https://www.exemplo.com",
				rules: {
					valid: "URL deve ser válido.",
				},
			},
		},
		save_changes: "Salvar mudanças",
		delete: {
			title: "Excluir conta",
			btn: "Excluir conta",
			warning: "Este processo é irreversível!",
			addons: {
				title_singular: "Isso vai afetar %d addon",
				title_plural: "Isso vai afetar %d addons",
				deleted: "Deletado",
				transferred: "Trasferido para outros autores",
			},
		},
	},
	gallery: {
		title: "Galeria",
		max_items_per_row: "Máximo de itens por linha",
		stretched_switcher: "Visualização completa de largura",
		animated_switcher: "Reproduzir texturas animadas",
		share: "Compartilhar textura",
		to_top: "Retornar ao início da página",
		share_link_copied_to_clipboard: "Link de compartilhamento copiado para a área de transferência",
		authors_copied_to_clipboard:
			"Autores do envio de textura copiados para a área de transferência",
		loading_message: "Carregando resultados da galeria…",
		error_message: {
			texture_not_done: "Textura não concluída!",
			user_anonymous: "Anônimo",
			user_not_found: "Usuário desconhecido",
			contribution_not_found: "Nenhuma contribuição encontrada no banco de dados!",
			search_failed: "Falha ao pesquisar",
		},
		category: {
			search: "Buscar",
			tag: "Tags",
			mc_version: "Versão do Minecraft",
			edition: "Edição",
			pack: "Pacote",
		},
		sort: {
			name_asc: "Nome (A → Z)",
			name_desc: "Nome (Z → A)",
			id_asc: "ID de Textura (menor → maior)",
			id_desc: "ID de textura (maior → menor)",
			contrib_desc: "Contribuição Recente",
		},
		tooltip: {
			modded: "Textura modificada",
			mojang: "Mojang Studios",
			ignored: "Textura ignorada",
		},
		all: "Tudo",
		latest: "Mais recentes",
		clear_cache: "Limpar Cache da Galeria",
		result_stats_singular: "Textura %COUNT% encontrada em %SECONDS% segundos",
		result_stats_plural: "Texturas %COUNT% encontradas em %SECONDS% segundos",
		modal: {
			no_contributions: "Nenhuma contribuição encontrada",
			image_alt_text: "Textura %NAME% para o pacote %PACK%",
			loading: "Carregando textura…",
			ignored: "Esta textura foi ignorada e pode não ser ampliada para todos os projetos!",
			tabs: {
				information: "Informações",
				authors: "Autores",
				animation: "Animação",
			},
			info: {
				texture: "Textura",
				uses: "Usos",
				paths: "Caminhos",
			},
			animation: {
				texture_mcmeta: "MCMETA",
			},
			data: {
				contribution_id: "ID de contribuição",
				date: "Data",
				authors: "Autor(es)",
				id: "ID",
				name: "Nome",
				tags: "Tags/Tipos",
				use_id: "ID do uso",
				use_name: "Nome do uso",
				edition: "Edição",
				texture_id: "ID da textura",
				path_id: "ID do caminho",
				resource_pack_path: "Caminho do pacote de recursos",
				mc_versions: "Versão(ões) do Minecraft",
			},
		},
	},
	addons: {
		titles: {
			submit: "Enviar um novo addon",
			edit: "Editar addon",
			submissions: "Envios de addon",
			details: "Detalhes",
		},
		remove: {
			title: "Confirmar exclusão",
			description: '"%s" será deletado para sempre. Isso não pode ser desfeito.',
		},
		general: {
			loading_addon: "Carregando addon",
			no_submissions: "Você não tem nenhum addon enviado!",
			go_to_addon: "Ver lista pública de addons",
			rules: "Certifique-se de ler as regras sobre addons antes de enviar",
			title: "Geral",
			name: {
				label: "Nome do addon",
				hint: "É preferível um nome mais curto.",
				rules: {
					name_required: "É necessário um nome.",
					name_too_big: "O nome do addon deve ter menos de %s caracteres.",
					name_too_small: "O nome do addon deve ter no mínimo %s caracteres.",
					name_unavailable: "Este nome já está em uso!",
				},
			},
			slug: {
				label: "Slug do addon",
				hint: "Alterar isto quebrará os links antigos!",
			},
			reason: {
				title: "Motivo da atualização",
				text: "Por favor, conte-nos o que você atualizou para tornar a análise do seu addon mais fácil!",
				required: "Uma razão para atualizar é necessária",
				bounds: "Motivo da atualização deve ter entre %s e %s caracteres",
			},
			authors: {
				label: "Selecionar autores do addon",
				hint: "Qualquer autor pode modificar o addon após seu envio! | Se você não encontrar ninguém na lista que deveria estar nela, contate um administrador ou desenvolvedor",
			},
		},
		info: {
			title: "Informação",
			description: {
				placeholder: "Descrição do addon",
				hint: "Você pode usar marcação HTML para melhorar sua descrição!",
				rules: {
					description_required: "A descrição é necessária",
					description_too_big: "A descrição deve ter menos de %s caracteres",
					description_too_small: "A descrição deve ter ao menos %s caracteres",
				},
			},
			embed_description: {
				label: "Descrição atribuída",
				hint: "Descrição vista ao compartilhar o addon em mídias sociais",
				rules: {
					too_big: "A descrição atribuída deve ter menos de %s caracteres",
				},
			},
		},
		images: {
			title: "Capturas de tela",
			header: {
				labels: {
					drop: "Clique para selecionar a imagem do cabeçalho",
					normal: "Imagem de cabeçalho",
					replace: "Substituir imagem de cabeçalho",
				},
				rules: {
					image_size:
						"O tamanho da imagem deve ser menor que %s KB! Use https://compressor.io/ para comprimi-la.",
					image_ratio:
						"Proporção errada: a imagem fornecida não tem uma proporção lateral de 16:9.",
					image_required: "Uma imagem de cabeçalho é necessária.",
					jpeg: "A imagem deve ser um JPEG com perdas.",
					compress: "Você pode compactar imagens usando https://compressor.io/",
				},
				status: {
					upload: "Imagem de cabeçalho carregada com sucesso",
					remove: "Imagem de cabeçalho removida com sucesso",
				},
			},
			screenshots: {
				labels: {
					drop: "Clique para selecionar imagens adicionais",
					normal: "Imagem(ns) adicional(is)",
					replace: "Substituir imagem(ns) adicional(is)",
				},
				rule: "Proporção errada: Imagem(ns) sem uma proporção lateral de 16:9 foram removidas.",
				status: {
					upload: "Captura de tela carregada com sucesso",
					remove: "Captura de tela removida com sucesso",
				},
			},
		},
		compatibility: {
			title: "Compatibilidade",
			optifine: {
				label: "Requer OptiFine",
			},
			editions: {
				label: "Edições com suporte",
			},
			packs: {
				label: "Pacotes com suporte",
			},
		},
		downloads: {
			title: "Downloads",
			add_group: "Adicionar grupo de downloads",
			add_item: "Adicionar download ao grupo",
			remove_group: "Remover grupo de downloads e itens",
			remove_item: "Remover download do grupo",
			name: {
				placeholder: "CurseForge, GitHub…",
				label: "Nome",
				rules: {
					name_required: "Um nome é necessário.",
					name_cannot_be_empty: "O nome não pode ser vazio.",
				},
			},
			link: {
				placeholder: "https://www.exemplo.com",
				label: "Link",
				rule: "URL deve ser válido.",
			},
		},
		status: {
			approved: "Aprovado",
			denied: "Negado",
			pending: "Pendente",
			archived: "Arquivado",
		},
	},
	review: {
		titles: {
			addons: "Analisar addons",
			pending: "Esperando aprovação",
			denied: "Negado",
			approved: "Aprovado",
			archived: "Arquivado",
		},
		reason_modal: {
			deny_title: "Negar addon",
			archive_title: "Arquivar add-on",
			label: "Escreva um motivo…",
			rule: "Qualquer motivo pode ser dado",
		},
		labels: {
			pending: "Não há nenhum addon pendente no momento!",
			denied: "Não há nenhum addon negado no momento!",
			archived: "Não há nenhum addon arquivado no momento!",
			approved: "Não há nenhum addon aprovado no momento!",
			load_approved: "Carregar addons aprovados",
		},
		addon: {
			titles: {
				last_updated: "Última atualização %s",
				unknown_date: "Última atualização do addon desconhecida",
				compatibility: "Compatibilidade",
				author_singular: "Autor",
				author_plural: "Autor(es)",
				description: "Descrição",
				download_singular: "Download",
				download_plural: "Downloads",
			},
			labels: {
				optifine: "OptiFine",
				approved_by: "Aprovado por %s",
				denied_by: "Negado por %s",
				archived_by: "Arquivado por %s",
				unknown_status: "Estado de revisão desconhecido (%s)",
				reason: "Motivo",
				no_reason: "Nenhum motivo fornecido",
			},
		},
	},
	posts: {
		titles: {
			list: "Todas as publicações",
			edit: "Editar publicação",
			new: "Criar nova publicação",
		},
		status: {
			published: "Publicado em %s",
			draft: "Rascunho",
		},
		loading: "Carregando publicação…",
		go_to_post: "Ver publicação divulgada",
		general: {
			heading: "Geral",
			title: {
				label: "Título da publicação",
				placeholder: "Faithful Smart Fridge - Alpha 1",
			},
			permalink: {
				label: "Link permanente",
				placeholder: "/faithfulsmartfridge/A1",
			},
			header_img: {
				label: "Imagem do cabeçalho (opcional)",
				hint: "Nota: Isto deve ser enviado separadamente",
				placeholder: "https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg",
			},
			date: {
				label: "Publicar data de lançamento",
			},
			discontinued: {
				label: "Descontinuada",
				hint: "Se marcada, a publicação será registrada com descontinuada",
			},
			description: {
				placeholder: "Descrição da publicação",
				hint: "Você pode usar marcação HTML para melhorar sua descrição!",
			},
		},
		download: {
			heading: "Downloads",
			add_category: "Adicionar categoria de download",
			add_item_to_category: "Adicionar download à categoria",
			add_single_item: "Adicionar download único",
			remove_category: "Remover categoria de download e itens",
			remove_item_in_category: "Remover download da categoria",
			remove_single_item: "Remover download individual",
			category: "Baixar nome da categoria",
			name: "Nome do download",
			link: "Link de download",
			link_placeholder: "https://www.exemplo.com",
		},
		changelog: {
			heading: "Histórico de mudanças",
			add_category: "Adicionar categoria de histórico de mudanças",
			add_item: "Adicionar item do histórico de mudanças",
			remove_category: "Remover categoria de histórico de mudanças",
			remove_item: "Remover item do histórico de mudanças",
			import_json: "Importar JSON",
			form_levels: {
				primary: "Categoria primária",
				secondary: "Categoria secundária",
				item_category: "Categoria do Item (Autores)",
				item: "Item (Autores)",
			},
		},
		changelog_generator: {
			heading: "Gerar histórico de mudanças",
			date: "Data desde o último histórico de mudanças",
			pack: "Pacote de histórico de mudanças",
			copy: "Copiar para a área de transferência",
			categorize: "Categorizar automaticamente o histórico de mudanças por tipo (experimental)",
			categorize_warning:
				"Categorização por tipo pode ser imprecisa devido a como as contribuições são monitoradas!",
			download: "Baixar histórico de mudanças",
			warning: "Pedimos que revise manualmente o histórico de mudanças antes de importá-lo!",
		},
	},
	database: {
		search: "Buscar",
		anonymous: "Anônimo",
		nameless: "Sem nome",
		summary: "Resumo",
		confirm_deletion: "Confirmar exclusão",
		ask_deletion: "Você deseja excluir %s (%d)?",
		contributions: {
			title: "Contribuições",
			contributors: "Contribuidores",
			add_contributions: "Adicionar novar contribuições",
			edit_contribution: "Editar contribuição",
			delete_contribution: "Deletar contribuição",
			pack_filter: "Filtrar por pacote",
			user_filter: "Usuários",
			texture_filter: "Texturas",
			select_user: "Selecionar usuário(s)",
			contribution_count_singular: "%d contribuição",
			contribution_count_plural: "%d contribuições",
			authorless: "Nenhum autor adicionado",
			contribution_result: "Resultados da contribuição",
			search_contributions: "Buscar contribuições",
			modal: {
				add_new_contribution: "Adicionar nova contribuição",
				clone_contribution: "Clonar a contribuição",
				one_contributor: "Por favor escolha pelo menos um contribuidor",
				id: "ID de contribuição",
				id_hint: "Mudar o ID da contribuição pode quebrar tudo!",
				pack: "Pacote de recursos",
				texture_id: "ID da textura",
				texture_ids: "IDs de textura",
				increment_texture: "ID da textura incrementada",
				decrement_texture: "Diminuir ID da textura",
				id_field_errors: {
					one_required: "Pelo menos um ID de textura ou um intervalo de identificação é necessário",
					incorrect_value: "ID ou ID do %value% de textura incorretos",
				},
			},
		},
		users: {
			title: "Usuários",
			role_filter: "Filtrar por função",
			search_username: "Buscar nome de usuário",
			user_result: "Resultados do usuário",
			modal: {
				add_user: "Adicionar novo usuário",
				edit_user: "Editar usuário",
				delete_user: "Excluir conta",
				id: "ID do Discord",
				id_hint: "Mudar o ID do Discord vai atualizar todas as contribuições e addons relacionados",
				username: "Nome de usuário",
				uuid: "UUID do perfil do Minecraft",
				roles: "Função do usuário",
				anonymous: "Anônimo",
			},
		},
		textures: {
			title: "Texturas",
			add_texture: "Adicionar nova textura",
			add_multiple: "Adicionar novas texturas",
			edit_texture: "Editar textura",
			texture_result: "Resultados da textura",
			tag_filter: "Filtrar por tag",
			search_texture: "Buscar nome de textura",
			add_success: "Textura(s) adicionada(s) com sucesso",
			delete_modal: {
				title_texture: "Deletar textura",
				title_use: "Deletar uso",
				title_path: "Deletar caminho",
				affected_uses: "Usos afetados",
				affected_paths: "Caminhos afetados",
				affected_contributions: "Contribuições afetadas",
			},
			modal: {
				title: "Texturas",
				subtitle: "Usos e Caminhos",
				tagless: "Nenhuma tag adicionada",
				copy_button: "Copiar dados da textura como JSON",
				json_button: "Importar dados em JSON",
				persist_button: "Persistir em salvar",
				copy_json_data: "Dados JSON copiados para área de transferência",
				id_hint: "Alterar o ID da textura pode quebrar tudo!",
				id: "ID da textura",
				name: "Nome da textura",
				tags: "Tags da textura",
			},
			uses: {
				title: "Usos",
				singular: "Uso",
				plural: "Usos",
				add_use: "Adicionar novo uso",
				edit_use: "Editar uso",
				add_edition_use: "Adicionar uso automático de %edition%",
				no_use_found: "Nenhum uso encontrado para essa textura.",
				id_hint: "Alterar o ID do uso pode quebrar tudo",
				id: "ID do uso",
				name: "Nome do uso",
				edition: "Edição do uso",
			},
			paths: {
				title: "Caminhos",
				singular: "Caminho",
				plural: "Caminhos",
				add_path: "Adicionar novo caminho",
				edit_path: "Editar caminho",
				no_path_found: "Nenhum caminho encontrado para esse uso.",
				id_hint: "Alterar o ID do caminho pode quebrar tudo!",
				id: "ID do caminho",
				name_hint: "O caminho deve começar na pasta-mãe (ex: assets/…)",
				name_prefill: "Digite isso primeiro para gerar mais campos!",
				name: "Caminho",
				versions: "Versões",
				mcmeta: "Animado",
			},
			merge_textures: {
				title: "Mesclar texturas",
				warning: "Isto vai deletar a textura fonte e não poderá ser desfeito!",
				source: "ID da textura fonte",
				destination: "Destinação da ID da textura",
				invalid_id: "ID da textura inválida",
			},
		},
		versions: {
			title: "Versões",
			edition_filter: "Filtrar por edição",
			version_result: "Resultados da versão",
			exists: "O nome da versão já existe",
			path_count_singular: "caminho %d",
			path_count_plural: "caminhos %d",
			no_paths: "Sem caminhos associados",
			modal: {
				title: "Editar versão do Minecraft",
				name: "Nome da versão do Minecraft",
				edition: "Versão do Minecraft",
				warning: "Por favor não se esqueça de atualizar todos o nomes das ramificações do GitHub!",
			},
			add: {
				title: "Adicionar nova versão do Minecraft",
				success: "Versão adicionada com sucesso",
				new_edition: "Edição da nova versão",
				template_version: "Versão modelo",
				new_version: "Nome da nova versão",
			},
			delete: {
				title: "Deletar versão do Minecraft",
				description: "Você quer deletar a versão %VERSION% da edição %EDITION%?",
				no_affected_paths: "Nenhum caminho será afetado",
				affected_paths_singular: "%d caminho será afetado.",
				affected_paths_plural: "%d caminhos serão afetados.",
			},
		},
		packs: {
			title: "Pacotes",
			tag_filter: "Filtrar por tag",
			pack_result: "Resultados do pacote",
			modal: {
				add_pack: "Adicionar novo pacote",
				edit_pack: "Editar pacote",
				delete_pack: "Deletar pacote",
				id: "ID do pacote",
				id_creation_hint:
					"Um ID de Pacote pode ser especificado manualmente ou ser gerado automaticamente.",
				id_editing_hint: "Alterar o ID de um pacote pode quebrar tudo!",
				name: "Nome do pacote",
				tags: "Tags do pacote",
				resolution: "Resolução do pacote",
				color: "Cor do pacote",
				logo: "URL do logotipo do pacote",
				github: {
					title: "GitHub",
					title_hint: "Uma edição pode ser deixada em branco se ainda não tiver suporte.",
					length_notice: "Pelo menos um repositório do GitHub precisa estar presente.",
					organization: "Organização",
					repository: "Repositório",
				},
				delete_hint:
					"Deletar um pacote vai removê-lo da galeria de texturas e dos bots do Discord, mas não vai afetar seus repositórios no GitHub.",
			},
			submissions: {
				title: "Informações de envio",
				delete_submission: "Deletar informações de envio",
				add_submission: "Adicionar informações de envio",
				edit_submission: "Editar informações de envio",
				reference_pack: "Pacote de referência",
				reference_hint: "Pacote para comparar com as atribuições de envios.",
				contributor_role: "ID da função do contribuidor",
				time_to_results: "Tempo para os resultados",
				time_hint: "Os atrasos são medidos em dias.",
				channels: {
					title: "Canais do Discord",
					title_hint:
						"Ative o Modo de Desenvolvedor e clique com o botão direito em um canal para obter IDs de canal.",
					submit: "Canal de envio",
					results: "Canal de resultados",
				},
				delete_warning: "Isto irá remover %d contribuições!",
			},
		},
		settings: {
			title: "Configurações",
		},
	},
};
